# Copyright 2023 Airbus
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  application:
    name: {{ .Values.service.name }}

# Logging
logging:
  config: {{ .Values.logConfig }}

# REST controller
server:
  port: {{ .Values.service.port }}

# Native API config
native-api:
  # major version (used as part of the API base path)
  major-version: v1
  # version (to communicate minor changes that are compatible with the major version)
  version: 1.0
  # configuration for internal interfacing to PRIP
  prip-protocol: {{ .Values.nativeapi.prip.protocol }}
  prip-host: {{ .Values.nativeapi.prip.host }}
  prip-port: {{ .Values.nativeapi.prip.port }}
  # configuration to create PRIP metadata and download links that are externaly accessible
  external-prip-protocol: {{ .Values.nativeapi.external.protocol }}
  external-prip-host: {{ .Values.nativeapi.external.host }}
  external-prip-port: {{ .Values.nativeapi.external.port }}
  # whether to include the attributes/values of the 'Attributes' collection of the PRIP response into the STAC response
  include-additional-attributes: true
  # default limit
  defaultLimit: {{ .Values.nativeapi.defaultLimit }}
  maxLimit: {{ .Values.nativeapi.maxLimit }}
  rootCatalogId: {{ .Values.nativeapi.rootCatalog.id }}
  rootCatalogTitle: {{ .Values.nativeapi.rootCatalog.title }}
  rootCatalogDescription: {{ .Values.nativeapi.rootCatalog.description }}
  serviceDocLink: {{ .Values.nativeapi.serviceDoc.link }}
  serviceDocMimeType: {{ .Values.nativeapi.serviceDoc.mimeType }}
  hostname: {{ .Values.nativeapi.hostname }}
  collections:
{{- range $key, $val := .Values.nativeapi.collections }}
    {{ $key}}:
      title: {{ $val.title | quote }}
      description: {{ $val.description | quote }}
      license: {{ $val.license | quote }}
      catalog: {{ $val.catalog | quote }}
{{- end}}
  lutConfigs: 
  {{- range $key, $val := .Values.nativeapi.lutConfigs }}
    "{{ $key}}":
      {{- range $config := $val}}
        - {{ $config }}
      {{- end}}
  {{- end}}
