#TODO: figure out why I need this here and in bootstrap.yml
spring:
  main:
    banner-mode: "off"
  application:
    name: s1pdgs-prip-worker 
  
# Logging config
logging:
  config: ${log4j_config:log/log4j2.yml}

# MQI config
mqi:
  # The host and port for querying MQI server
  host-uri: http://localhost:8081
  # The maximal number of consecutive retries following a MQI request error, default is 3
  max-retries: 100
  # Time between retries in milliseconds, default is 1000
  tempo-retry-ms: 2000

# Metadata Catalog config
metadata:
  # Metadata catalog hostname
  host: ${catalog_rest_host}
  # The maximal number of consecutive retries
  rest-api_nb-retry: {{ .Values.metadataCatalog.restApiNbRetry }} 
  # Time between retries in milliseconds
  rest-api_tempo-retry-ms: {{ .Values.metadataCatalog.restApiTempoRetryMs }} 
  
# Elastic Search config
elasticsearch:
  # Host of Elasticsearch cluster
  host: ${elastic_host}
  # Port of Elasticsearch cluster
  port: ${elastic_port}
  # Timeout in milliseconds of connection to the cluster
  connect-timeout-ms: 2000
  # Timeout in milliseconds of the socket to the cluster
  socket-timeout-ms: 10000

# Kafka config
kafka:
  # host:port to use for establishing the initial connection to the Kafka cluster
  bootstrap-servers: ${kafka_bootstrap-servers}
  # Hostname
  hostname: ${HOSTNAME}
  # Topic name for the errors
  error-topic: ${kafka_topic_errors}
  # Kafka Producer config
  producer:
    # When greater than zero, enables retrying of failed sends
    max-retries: 10
  
# PRIP Worker config
prip-worker:
  # Hostname
  hostname: ${HOSTNAME}
  # Number of retries when Metadata is unavailable
  metadata-unavailable-retries-number: 10
  # Time interval between retries when Metadata is unavailable
  metadata-unavailable-retries-interval-ms: 5000
  # Configuration for Publishing Job listening
  publishing-job-listener:
    # Polling interval for MQI messages in millis, default is 1000
    polling-interval-ms: 500
    # Initial waiting time before polling MQI in millis
    polling-initial-delay-ms: 5000
  # Product identification map by product type
  product-type-regexp:
    l0-std: (S[1-6]|IW|EW|EN|RF|WV|N[1-6])_RAW__0S
    l0-ann: (S[1-6]|IW|EW|WV)_RAW__0A
    l0-cal: (S[1-6]|IW|EW|WV)_RAW__0C
    l0-noise: (S[1-6]|IW|EW|WV)_RAW__0N
    l0-gps: GP_RAW__0_
    l0-hktm: HK_RAW__0_
    l1: (S[1-6]|IW|EW|WV)_(SLC_|GRDF|GRDH|GRDM|RTC_)_1(A|S)
    l2: (S[1-6]|IW|EW|WV)_(OCN_)_2(A|S)
    aux-safe: AUX_(PP1|CAL|INS|PP2|SCS|WND|WAV|ICE|ECE)
    aux-eof: AUX_(RESATT|PREORB|POEORB|RESORB)
  # Map metadata catalog fields to PRIP catalog fields in the notation attr_NAME_TYPE with possible types string, long, double, boolean, date
  metadata-mapping:
    l0-std:
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_operationalMode_string: operationalMode
      attr_swathIdentifier_string: swathIdentifier
      attr_productClass_string: productClass
      attr_productConsolidation_string: productConsolidation
      attr_instrumentConfigurationID_string: instrumentConfigurationId
      attr_missionDatatakeID_long: missionDataTakeId
      attr_sliceProductFlag_boolean: sliceProductFlag
      attr_sliceNumber_long: sliceNumber
      attr_totalSlices_long: totalNumberOfSlice
      attr_polarisationChannels_string: polarisationChannels
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_coordinates_string: coordinates
      attr_productType_string: productType
    l0-ann:
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_operationalMode_string: operationalMode
      attr_swathIdentifier_string: swathIdentifier
      attr_productClass_string: productClass
      attr_productConsolidation_string: productConsolidation
      attr_instrumentConfigurationID_string: instrumentConfigurationId
      attr_missionDatatakeID_long: missionDataTakeId
      attr_sliceProductFlag_boolean: sliceProductFlag
      attr_sliceNumber_long: sliceNumber
      attr_totalSlices_long: totalNumberOfSlice
      attr_polarisationChannels_string: polarisationChannels
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_coordinates_string: coordinates
      attr_productType_string: productType
    l0-cal:
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_operationalMode_string: operationalMode
      attr_swathIdentifier_string: swathIdentifier
      attr_productClass_string: productClass
      attr_productConsolidation_string: productConsolidation
      attr_instrumentConfigurationID_string: instrumentConfigurationId
      attr_missionDatatakeID_long: missionDataTakeId
      attr_sliceProductFlag_boolean: sliceProductFlag
      attr_sliceNumber_long: sliceNumber
      attr_totalSlices_long: totalNumberOfSlice
      attr_polarisationChannels_string: polarisationChannels
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_coordinates_string: coordinates
      attr_qualityDataObjectID_string: qualityDataObjectID
      attr_qualityNumOfElement_long: qualityNumOfElement
      attr_qualityNumOfMissingElements_long: qualityNumOfMissingElements
      attr_qualityNumOfCorruptedElements_long: qualityNumOfCorruptedElements
      attr_qualityNumOfRSIncorrigibleElements_long: qualityNumOfRSIncorrigibleElements
      attr_qualityNumOfRSCorrectedElements_long: qualityNumOfRSCorrectedElements
      attr_qualityNumOfRSCorrectedSymbols_long: qualityNumOfRSCorrectedSymbols     
      attr_productType_string: productType
    l0-noise:
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_operationalMode_string: operationalMode
      attr_swathIdentifier_string: swathIdentifier
      attr_productClass_string: productClass
      attr_productConsolidation_string: productConsolidation
      attr_instrumentConfigurationID_string: instrumentConfigurationId
      attr_missionDatatakeID_long: missionDataTakeId
      attr_sliceProductFlag_boolean: sliceProductFlag
      attr_sliceNumber_long: sliceNumber
      attr_totalSlices_long: totalNumberOfSlice
      attr_polarisationChannels_string: polarisationChannels
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_coordinates_string: coordinates
      attr_qualityDataObjectID_string: qualityDataObjectID
      attr_qualityNumOfElement_long: qualityNumOfElement
      attr_qualityNumOfMissingElements_long: qualityNumOfMissingElements
      attr_qualityNumOfCorruptedElements_long: qualityNumOfCorruptedElements
      attr_qualityNumOfRSIncorrigibleElements_long: qualityNumOfRSIncorrigibleElements
      attr_qualityNumOfRSCorrectedElements_long: qualityNumOfRSCorrectedElements
      attr_qualityNumOfRSCorrectedSymbols_long: qualityNumOfRSCorrectedSymbols     
      attr_productType_string: productType
    l0-gps:
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_productType_string: productType
    l0-hktm:
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_productType_string: productType
    l1:
      attr_processingDate_date: creationTime
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_operationalMode_string: operationalMode
      attr_swathIdentifier_string: swathIdentifier
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_coordinates_string: coordinates
      attr_instrumentConfigurationID_string: instrumentConfigurationId
      attr_missionDatatakeID_long: missionDataTakeId
      attr_polarisationChannels_string: polarisationChannels
      attr_productClass_string: productClass
      attr_productComposition_string: productComposition
      attr_productType_string: productType
      attr_timeliness_string:  safeTimeliness
      attr_sliceProductFlag_boolean: sliceProductFlag
      attr_segmentStartTime_date: segmentStartTime
      attr_sliceNumber_long: sliceNumber
      attr_totalSlices_long: totalNumberOfSlice
    l2:
      attr_processingDate_date: creationTime
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_beginningDateTime_date: startTime
      attr_endingDateTime_date: stopTime
      attr_startTimeFromAscendingNode_double: startTimeANX
      attr_completionTimeFromAscendingNode_double: stopTimeANX
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_operationalMode_string: operationalMode
      attr_swathIdentifier_string: swathIdentifier
      attr_orbitNumber_long: absoluteStartOrbit
      attr_relativeOrbitNumber_long: relativeStartOrbit
      attr_cycleNumber_long: cycleNumber
      attr_orbitDirection_string: pass
      attr_coordinates_string: coordinates
      attr_instrumentConfigurationID_string: instrumentConfigurationId
      attr_missionDatatakeID_long: missionDataTakeId
      attr_polarisationChannels_string: polarisationChannels
      attr_productClass_string: productClass
      attr_productComposition_string: productComposition
      attr_productType_string: productType
      attr_timeliness_string:  safeTimeliness
      attr_sliceProductFlag_boolean: sliceProductFlag
      attr_segmentStartTime_date: segmentStartTime
      attr_sliceNumber_long: sliceNumber
      attr_totalSlices_long: totalNumberOfSlice
    aux-safe:
      attr_processingDate_date: processingDate
      attr_processingCenter_string: site
      attr_processorName_string: processorName
      attr_processorVersion_string: processorVersion
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_instrumentShortName_string: instrumentShortName
      attr_productType_string: productType
      attr_beginningDateTime_date: validityStartTime
      attr_productGeneration_date: creationTime
      attr_instrumentConfigurationID_string: instrumentConfigurationId
    aux-eof:
      attr_platformShortName_string: platformShortName
      attr_platformSerialIdentifier_string: platformSerialIdentifier
      attr_productType_string: productType
      attr_beginningDateTime_date: validityStartTime
      attr_endingDateTime_date: validityStopTime
      attr_processingCenter_string: site
      attr_processorVersion_string: processorVersion
      attr_processingDate_date: creationTime
    # Identifies products by their name whose footprint is not a polygon but a linestring
    footprint-is-linestring-regexp: S1.*(RF|WV)_RAW__0(A|C|N|S).*


# PRIP client config
prip-client:
  repository:
    # Maximum number of search hits that can be retrieved at a time
    max-search-hits: 1000

# Application status configuration
status:
  # (Fixed delay) period in milliseconds between 2 check if application shall be stopped or not, default is 3000
  delete-fixed-delay-ms: 3000
  # The number of consecutive processing errors leading to the state FATALERROR, default is 100
  max-error-counter-processing: 30
  # The number of consecutive MQI errors leading to the state FATALERROR, default is 10
  max-error-counter-mqi: 30

# REST controller
server:
  # Port used for publishing REST API
  port: 8080 