spring:
  main:
    banner-mode: "off"
  application:
    name: s1pdgs-l1-production-trigger
    
# Logging
logging:
  config: ${log4j_config:log/log4j2.yml}

mqi:
  # The host and port for querying MQI server
  host-uri: http://localhost:8081
  # The maximal number of consecutive retries following a MQI request error, default is 3
  max-retries: 45
  # Time between retries in milliseconds, default is 1000
  tempo-retry-ms: 2000
  # For filtering messages, allowing or disallowing messages of specific product family with filename matching the regular expression
  message-filter:
    # Filter for dis/allowing specific files
  - productFamily: L0_SLICE
    disallowRegex: S1._RF_RAW_.*\.SAFE

metadata:
  # Metadata Catalog host
  host: ${catalog_rest_host}
  # Maximal number of retries when query fails
  rest-api_nb-retry: {{ .Values.metadataCatalog.restApiNbRetry }}
  # Temporisation in ms between 2 retries
  rest-api_tempo-retry-ms: {{ .Values.metadataCatalog.restApiTempoRetryMs }}

# Kafka config
kafka:
  # host:port to use for establishing the initial connection to the Kafka cluster
  bootstrap-servers: ${kafka_bootstrap-servers}
  # Hostname
  hostname: ${HOSTNAME}
  # Topic name for the errors
  error-topic: ${kafka_topic_errors}
  # Kafka Producer config
  producer:
    # When greater than zero, enables retrying of failed sends
    max-retries: 10

# Applicative Catalog config
appcatalog:
  # URI of the applicative data catalog APIs
  host-uri: http://s1pro-app-catalog-svc:8080
  # Number of max retries to connect API
  max-retries: 3
  # TempoRetry rate for retries to connect API
  tempo-retry-ms: 1000
  # Timeout of connections to the API
  tm-connect-ms: 5000

# Application status configuration
status:
  # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not, default is 3000
  delete-fixed-delay-ms: 1800000
  # The number of consecutive processing errors leading to the state FATALERROR, default is 100
  max-error-counter-processing: 3
  # The number of consecutive MQI errors leading to the state FATALERROR, default is 100
  max-error-counter-mqi: 30

tasktable:
  # Location of the routing file
  pathroutingxmlfile: /app/config/routing.xml
  # Template for routing based tasktable mapping
  routingKeyTemplate: $(product.acquistion)_$(product.satelliteId)
  
process:
  # Level for job generator, possible values: L0, L0_SEGMENT, L1, L2, SPP_MBU, SPP_OBS, S3_L0, S3_L1, S3_L2, S3_PDU
  level: L1
  # Product type to process, only for logging/reporting purposes
  product-type: L0Slice
  # Hostname
  hostname: ${HOSTNAME}
  # (Fixed delay) Delay in milliseconds between 2 next messages
  fixed-delay-ms: 200
  # Initial delay in missliseconds before the first next message
  initial-delay-ms: 5000
  # Product category to process, possible values: edrs-sessions, level-segments, level-products, spp-products
  category: level-products
  # Filename pattern for checking products for sea-coverage
  seaCoverageCheckPattern: ^neverMatching
  # Filename pattern for checking products for intersection of EW SLC mask
  l0EwSlcCheckPattern: ^S1[AB]_EW_RAW__0S.*\.SAFE$
  # The intersection check with the EW SLC mask is only applied for products whose task table name is contained in the following string 
  l0EwSlcTaskTableName: EW_RAW__0_SLC
  
