FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-core:develop as build

WORKDIR /app

#FROM registry.tools.s1pdgs.eu/wo7/docker_l1:dev
FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-container-l1:develop

WORKDIR /app
COPY --from=build /app/wrapper/target/s1pro-core-wrapper-*.jar s1pdgs-wrapper.jar
COPY --from=build /app/wrapper/config/start/start_l1.sh /app/start_l1.sh
RUN chmod +x /app/start_l1.sh
ENTRYPOINT "/app/start_l1.sh"
