ARG BRANCH
FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-core:${BRANCH} as build
ARG BRANCH_TEXT
WORKDIR /app

FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-container-l0-aiop:${BRANCH}
WORKDIR /app
RUN echo "${BRANCH_TEXT}" >> VERSION
COPY --from=build /app/wrapper/target/s1pro-core-wrapper-*.jar s1pdgs-wrapper.jar
COPY --from=build /app/wrapper/config/start/start_l0.sh /app/start_l0.sh
RUN chmod +x /app/start_l0.sh
ENTRYPOINT "/app/start_l0.sh"
