FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-core:latest as build

WORKDIR /app

FROM registry.tools.s1pdgs.eu/wo7/docker_l2:centos-7-6-1810
RUN yum install -y java-1.8.0-openjdk wget && yum clean all
WORKDIR /app
COPY --from=build /app/wrapper/target/s1pro-core-wrapper-*.jar s1pdgs-wrapper.jar
COPY --from=build /app/wrapper/config/start/start_l2.sh /app/start_l2.sh
RUN chmod +x /app/start_l2.sh
ENTRYPOINT "/app/start_l2.sh"
