FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-core:s1pro-003-s1pro-263-c as build

WORKDIR /app

#FROM registry.tools.s1pdgs.eu/wo7/docker_l0aiop:dev
FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-container-l0-aiop:develop

WORKDIR /app
COPY --from=build /app/wrapper/target/s1pro-core-wrapper-*.jar s1pdgs-wrapper.jar
COPY --from=build /app/wrapper/config/start/start_l0.sh /app/start_l0.sh
RUN chmod +x /app/start_l0.sh
ENTRYPOINT "/app/start_l0.sh"
