FROM registry.tools.s1pdgs.eu/werum/processing/s1pro-core:s1pro-003_b as build

WORKDIR /app

FROM registry.tools.s1pdgs.eu/wo7/docker_l1:dev
RUN yum install -y java-1.8.0-openjdk wget && yum clean all
WORKDIR /app
COPY --from=build /app/wrapper/target/s1pro-core-wrapper-*.jar s1pdgs-wrapper.jar
COPY --from=build /app/wrapper/config/start/start_l1.sh /app/start_l1.sh
RUN chmod +x /app/start_l1.sh
ENTRYPOINT "/app/start_l1.sh"
