# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: rs-prip-frontend
  port: 8080
  
replicaCount: 1
logLevel: ${logLevel:DEBUG}
logConfig: ${logConfig:log/log4j2.yml}

processing:
  namespace: processing
  
elasticsearch:
  host: elasticsearch-master
  port: 9200
  connect-timeout-ms: 2000
  socket-timeout-ms: 10000
  
worker:
  label:
    key: node-role.kubernetes.io/worker
    value: infra

image:
  registry: artifactory.coprs.esa-copernicus.eu
  repository: werum-docker
  
  name: rs-core-prip-frontend
  tag: develop
  
  imagePullSecrets: artifactory
  
prip-frontend:
  debug-support: false

resources:
  cpu:
    request: "100m"
    limit: "500m"
  ram:
    request: "315Mi"
    limit: "1260Mi"
  javaOpts:
#   xms: "256m"
    xmx: "512m"
