# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: rs-prip-frontend
  port: 8080
  
replicaCount: 1
logLevel: DEBUG
logConfig: log/log4j2.yml

processing:
  namespace: processing
  
image:
  registry: artifactory.coprs.esa-copernicus.eu
  repository: rs-docker
  
  name: rs-core-prip-frontend
  tag: {{CHART_VERSION}}
  
  imagePullSecrets: spring-cloud-dataflow-registry-dockersecret
  
update:
  maxSurge: 100%
  maxUnavailable: 50% 

elasticsearch:
  host: elasticsearch-processing-es-http.database.svc.cluster.local
  port: 9200
  timeout:
    connection: 2000
    socket: 10000

prip:
  debug: false

resources:
  cpu:
    request: "100m"
    limit: "500m"
  ram:
    request: "315Mi"
    limit: "1260Mi"
  javaOpts:
#   xms: "256m"
    xmx: "512m"
