spring:
  application:
    name: s1pdgs-inbox-polling
  datasource:
    url: jdbc:hsqldb:file:/app/db/db;create=true
      
logging:
  config: log4j2.yml

# KAFKA
kafka:
  bootstrap-servers: localhost:9093                              # the bootstrap servers for KAFKA
  group-id: ingestors
  max-retries: 10
  topic: t-pdgs-ingestion
  
# REST controller
server:
  port: 8081      

  