image: docker:latest

services:
  - name: docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  MODULE: s1pro-core
  BRANCH: develop

stages:
  - build
  - module
  - test
  - deploy

before_script:
    - alias dockerbuild='docker build --network host --pull --build-arg BRANCH=$BRANCH --build-arg BRANCH_TEXT=$BRANCH'
    - docker login -u "$CI_REGISTRY_USERNAME" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# Build procedure for master branch
build-master:
  stage: build
  script:
    - dockerbuild -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE"
  only:
    - master

# Build procedure for develop branch (and all others)
build-develop:
  stage: build
  script:
    - dockerbuild --target final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE:$CI_COMMIT_REF_SLUG"
  except:
    - master

include:
  - local: applicative-catalog/.gitlab-ci.yml
  - local: archives/.gitlab-ci.yml
  - local: compression/.gitlab-ci.yml
  - local: error-repository/.gitlab-ci.yml
  - local: ingestor/.gitlab-ci.yml
  - local: job-generator/.gitlab-ci.yml
  - local: metadata-catalog/.gitlab-ci.yml
  - local: mqi-server/.gitlab-ci.yml
  - local: scaler/.gitlab-ci.yml
  - local: queue-watcher/.gitlab-ci.yml
  - local: wrapper/.gitlab-ci.yml
