image: docker:latest

services:
  - name: docker:dind
#    command: ["--mtu=1300"]

   
variables:
  DOCKER_HOST: tcp://localhost:2375
  MODULE: s1pro-core
  
  # These variables are normally set by the environment. For some reason this is not working for the develop branch however.
  # This is a workaround to ensure it is working in both branches (S1PRO-59)
  CI_REGISTRY_USERNAME: git_werum
  CI_REGISTRY: registry.tools.s1pdgs.eu
  
stages:
  - build
  - module
  - test
  - deploy

before_script:
    #- docker login -u "$CI_REGISTRY_USERNAME" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    
    # Passwort set as project specific build environment. 
    # This is a workaround to ensure it is working in both branches (S1PRO-59)
    - docker login -u "$CI_REGISTRY_USERNAME" -p "$TEMP_PWD" $CI_REGISTRY   
    
# Build procedure for master branch
build-master:
  stage: build
  script:
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE"
  only:
    - master

# Build procedure for develop branch (and all others)
build-develop:
  stage: build
  script:
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE:$CI_COMMIT_REF_SLUG"
  except:
    - master
            
include:
  - local: applicative-catalog/.gitlab-ci.yml
  - local: archives/.gitlab-ci.yml
  - local: ingestor/.gitlab-ci.yml
  - local: job-generator/.gitlab-ci.yml
  - local: metadata-catalog/.gitlab-ci.yml
  - local: mqi-server/.gitlab-ci.yml
  - local: scaler/.gitlab-ci.yml

# Wrapper is currently not building correctly.
#  - local: wrapper/.gitlab-ci.yml
