image: docker:latest

services:
  - name: docker:18.06-dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  MODULE: s1pro-core
  BRANCH: $CI_COMMIT_REF_SLUG
  VERSION: 0.14.0

stages:
  - build
  - module
  - test
  - deploy

before_script:
    - alias dockerbuild="docker build --network host --pull --build-arg BRANCH=$BRANCH --build-arg BRANCH_TEXT=$BRANCH --build-arg COMMIT_ID=$CI_COMMIT_SHA --build-arg VERSION=$VERSION"
    - alias # just for debugging purpose
    - docker login -u "$CI_REGISTRY_USERNAME" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - dockerbuild --target final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE:$CI_COMMIT_REF_SLUG"

include:
  - local: applicative-catalog/.gitlab-ci.yml
  - local: archives/.gitlab-ci.yml
  - local: disseminator/.gitlab-ci.yml
  - local: request-repository/.gitlab-ci.yml
  - local: ingestion-trigger/.gitlab-ci.yml
  - local: ingestion-worker/.gitlab-ci.yml
  - local: production-trigger/.gitlab-ci.yml
  - local: ipf-preparation-worker/.gitlab-ci.yml
  - local: metadata-catalog-trigger/.gitlab-ci.yml
  - local: metadata-catalog-worker/.gitlab-ci.yml
  - local: mqi-server/.gitlab-ci.yml
#  - local: scaler/.gitlab-ci.yml
  - local: queue-watcher/.gitlab-ci.yml
  - local: validation/.gitlab-ci.yml
  - local: compression-trigger/.gitlab-ci.yml
  - local: compression-worker/.gitlab-ci.yml
  - local: prip-trigger/.gitlab-ci.yml
  - local: prip-worker/.gitlab-ci.yml
  - local: prip-frontend/.gitlab-ci.yml
  - local: ipf-execution-worker/.gitlab-ci.yml
  - local: data-lifecycle-trigger/.gitlab-ci.yml
  - local: data-lifecycle-worker/.gitlab-ci.yml
