FROM obs-sdk:1.0.0 as build_lib_obs
WORKDIR /app

FROM maven:3.5.2-jdk-8-alpine as build
WORKDIR /app
COPY --from=build_lib_obs /app/libs/ /app/libs/
COPY pom.xml /app
RUN mvn dependency:go-offline
COPY src/ /app/src/
COPY dev/ /app/dev/
COPY test/ /app/test/
COPY config/ /app/config/
RUN	mvn -B package

FROM registry.geohub.space/wo7/docker_l1:dev
RUN yum install -y java-1.8.0-openjdk && yum clean all
WORKDIR /app
COPY --from=build /app/target/s1pdgs-wrapper-1.0.0.jar s1pdgs-wrapper.jar
COPY /config/log/log4j2.yml log4j2.yml
COPY /src/main/resources/application.yml application.yml
ENTRYPOINT /var/tmp/configure_pdgs_custom.sh pac1 8 && ulimit -s unlimited && java -Djava.security.egd=file:/dev/./urandom -jar /app/s1pdgs-wrapper.jar --spring.config.location=classpath:/application.yml
