FROM registry.geohub.space/wo7/repo-maven-all:latest as build
WORKDIR /app
COPY pom.xml /app
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
COPY src/ /app/src/
COPY dev/ /app/dev/
COPY test/ /app/test/
COPY config/ /app/config/
RUN	mvn -B -s /usr/share/maven/ref/settings-docker.xml package

FROM registry.geohub.space/wo7/docker_l0:dev
RUN yum install -y java-1.8.0-openjdk && yum clean all
WORKDIR /app
COPY --from=build /app/target/s1pdgs-wrapper-1.0.0.jar s1pdgs-wrapper.jar
COPY /config/log/log4j2.yml log4j2.yml
COPY /src/main/resources/application.yml application.yml
ENTRYPOINT /var/tmp/conf.sh && java -Djava.security.egd=file:/dev/./urandom -jar /app/s1pdgs-wrapper.jar --spring.config.location=classpath:/application.yml
