FROM openjdk:8-jre-slim

WORKDIR /app
COPY target/*native-api*.jar app.jar
COPY start.sh /app/start.sh

RUN mkdir config
COPY /src/main/resources/application.yml /app/config/application.yml

RUN mkdir openapi
COPY /src/main/resources/native-api_openapi.yml /app/openapi/native-api_openapi.yml

EXPOSE 8080

ENTRYPOINT "/app/start.sh"
