apiVersion: v1
appVersion: "develop"
description: S1PRO Inbox EDIP PEDC Polling Service
name: s1pro-ingestion-edip-pedc-trigger
version: 3.33.0-SNAPSHOT
maintainers:
  - name: Werum Software & Systems
