#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-queue-watcher
    
# Logging
logging:
  config: log4j2.yml

watcher:
  csvFile: /data/notificationSimulatorService.csv     

# File
file:
  mqi:
    host-uri: http://localhost:8081                               # the host and port for querying MQI server
    max-retries: 3                                                # the maximal number of consecutive retries following a MQI request error 
    tempo-retry-ms: 1000                                          # 
  product-categories:
    auxiliary-files:
      fixed-delay-ms: 500                                         # (fixed delay) Period in milliseconds between 2 polls of next message
    level-products:
      fixed-delay-ms: 500                                         # 
    level-segments:
      fixed-delay-ms: 500                                         # 
    compressed-products:
      fixed-delay-ms: 500                                         # 
        
