#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-queue-watcher
    
# Logging
logging:
  config: log4j2.yml
    

# File
file:
  file-with-manifest-ext: .safe                                   # Extension of the SAFE files
  manifest-filename: manifest.safe                                # Name of the manifest (with extension)
  mqi:
    host-uri: http://localhost:8081                               # the host and port for querying MQI server
    max-retries: 3                                                # the maximal number of consecutive retries following a MQI request error 
    tempo-retry-ms: 1000                                          # 
  product-categories:
    auxiliary-files:
      fixed-delay-ms: 500                                         # (fixed delay) Period in milliseconds between 2 polls of next message
      init-delay-poll-ms: 2000                                    # Initial delay in milliseconds before starting consuming message
    edrs-sessions:
      fixed-delay-ms: 500                                         # 
      init-delay-poll-ms: 2000                                    # 
    level-products:
      fixed-delay-ms: 500                                         # 
      init-delay-poll-ms: 2000                                    # 
    level-segments:
      fixed-delay-ms: 500                                         # 
      init-delay-poll-ms: 2000                                    # 
    compressed-products:
      fixed-delay-ms: 500                                         # 
      init-delay-poll-ms: 2000                                    # 
        
# REST controller
server:
  port: 8080                                                      # port used for publishing REST API
  
status:
  max-error-counter-processing: 3                                 # the number of consecutive processing errors leading to the state FATALERROR
  max-error-counter-mqi: 30                                       # the number of consecutive MQI errors leading to the state FATALERROR
  