# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  port: 8080

image:
  name: rs-core-mock-ftpserver

ftp:
  cpu:
    request: "100m"
    limit: "500m"
  ram:
    request: "10Mi"
    limit: "50Mi"