spring:
  cloud:
    function:
      definition: newInboxService
    stream:
      function:
        bindings:
          newInboxService-out-0: output
      bindings:
        output:
          destination: ingestiontrigger

server:
  port: 8080