spring:
  main:
    banner-mode: "off"
  application:
    name: {{ .Values.service.name }}

# Logging config
logging:
  config: {{ .Values.logConfig }}
  
# Elastic Search config
elasticsearch:
  # Host of Elasticsearch cluster
  host: {{ .Values.elasticsearch.host }}
  # Port of Elasticsearch cluster                                        
  port: {{ .Values.elasticsearch.port }}
  # Timeout in milliseconds of connection to the cluster
  connect-timeout-ms: {{ .Values.elasticsearch.connect-timeout-ms }}
  # Timeout in milliseconds of the socket to the cluster
  socket-timeout-ms: {{ .Values.elasticsearch.socket-timeout-ms }}
  
# PRIP Frontend config
prip-frontend:
  # Time in seconds until a download URL expires
  download-url-expiration-time-in-seconds: 600
  # Expose the debug support for OLingo (Default: false)
  debug-support: {{ .Values.prip-frontend.debug-support }}

# PRIP client config
prip-client:
  repository:
    # Maximum number of search hits that can be retrieved at a time
    max-search-hits: 1000

# REST controller
server:
  # Port used for publishing REST API
  port: {{ .Values.service.port }}

# Generated from obs-stream-parameters.properties  
obs:
  bucket:
    s3-pug: rs-s3-pug
    l0-slice: rs-l0-slices
    plan-and-report: rs-plans-and-reports
    s3-l0-zip: rs-s3-l0-zip
    edrs-session: rs-session-files
    l1-slice: rs-l1-slices
    l0-slice-zip: rs-l0-slices-zip
    s3-l2-nrt: 'rs-s3-l2-nrt '
    s3-granules: rs-s3-granules
    spp-mbu: rs-spp-mbu
    spp-obs: rs-spp
    l2-acn-zip: rs-l2-acns-zip
    s3-l1-nrt-zip: rs-s3-l1-nrt-zip
    s3-l1-stc-zip: rs-s3-l1-stc-zip
    l0-acn-zip: rs-l0-acns-zip
    s3-l2-stc: rs-s3-l2-stc
    invalid: rs-invalid
    failed-workdir: rs-failed-workdir
    s3-l2-ntc-zip: rs-s3-l2-ntc-zip
    s3-l1-nrt: rs-s3-l1-nrt
    debug: rs-debug
    s3-l1-stc: rs-s3-l1-stc
    s3-l0: rs-s3-l0
    s3-aux: rs-s3-aux
    auxiliary-file-zip: rs-auxiliary-files-zip
    l0-acn: rs-l0-acns
    ghost: rs-ghost
    l0-segment-zip: rs-l0-segments-zip
    s3-cal-zip: rs-s3-cal-zip
    plan-and-report-zip: rs-plans-and-reports-zip
    l2-slice-zip: rs-l2-slices-zip
    l0-segment: rs-l0-segments
    s3-cal: rs-s3-cal
    s3-aux-zip: rs-s3-aux-zip
    s3-pug-zip: rs-s3-pug-zip
    l1-acn-zip: rs-l1-acns-zip
    s3-l1-ntc: rs-s3-l1-ntc
    s3-l2-nrt-zip: rs-s3-l2-nrt-zip
    s3-l1-ntc-zip: rs-s3-l1-ntc-zip
    s3-granules-zip: rs-s3-granules-zip
    s3-l2-stc-zip: rs-s3-l2-stc-zip
    l0-blank-zip: rs-l0-blanks-zip
    l2-acn: rs-l2-acns
    s3-l2-ntc: rs-s3-l2-ntc
    auxiliary-file: rs-auxiliary-files
    l1-acn: rs-l1-acns
    l2-slice: rs-l2-slices
    l1-slice-zip: rs-l1-slices-zip
    l0-blank: rs-l0-blanks
    session-retransfer: rs-session-retransfer
    spp-obs-zip: rs-spp-zip
  user-secret: ${OBS_PASSWORD}
  disable-chunked-encoding: 'false'
  endpoint-region: eu-west-0
  user-id: ${OBS_USERNAME}
  endpoint: s3-master:9999
