spring:
  main:
    banner-mode: "off"
  application:
    name: rs-prip-frontend

# Logging config
logging:
  config: {{ .Values.logConfig }}
  
# Elastic Search config
elasticsearch:
  # Host of Elasticsearch cluster
  host: elasticsearch-master
  # Port of Elasticsearch cluster                                        
  port: 9200
  # Timeout in milliseconds of connection to the cluster
  connect-timeout-ms: 2000
  # Timeout in milliseconds of the socket to the cluster
  socket-timeout-ms: 10000
  
# PRIP Frontend config
prip-frontend:
  # Time in seconds until a download URL expires
  download-url-expiration-time-in-seconds: 600
  # Expose the debug support for OLingo (Default: false)
  debug-support: false

# PRIP client config
prip-client:
  repository:
    # Maximum number of search hits that can be retrieved at a time
    max-search-hits: 1000

# REST controller
server:
  # Port used for publishing REST API
  port: 8080 