kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.processing.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.processing.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.request_repository.ram.request }}
            cpu: {{ .Values.request_repository.cpu.request }}
          limits:
            memory: {{ .Values.request_repository.ram.limit }}
            cpu: {{ .Values.request_repository.cpu.limit }}
        volumeMounts:
        - name: logging-config-volume
          mountPath: /app/log
        - name: service-config-volume
          mountPath: /app/config
        - name: openapi-config-volume
          mountPath: /app/openapi
        env:
        - name: JAVA_XMS
          value: {{ .Values.request_repository.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.request_repository.javaOpts.xmx }}
        - name: mongodb.username
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: USERNAME
        - name: mongodb.password
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: PASSWORD
        ports:
        - name: web
          protocol: TCP
          containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      dnsPolicy: ClusterFirst
      subdomain: {{ .Values.service.port }}-svc
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: logging-config-volume
          configMap:
            name: {{ .Release.Name }}-logging-config
        - name: service-config-volume
          configMap:
            name: {{ .Release.Name }}-service-config
        - name: openapi-config-volume
          configMap:
            name: {{ .Release.Name }}-openapi-config
  serviceName: {{ .Values.service.port }}-svc
  revisionHistoryLimit: 10
