spring:
  application:
    name: s1pdgs-error-repo
    
logging:
  config: log4j2.yml

# REST controller
server:
  port: 8081      
  
# KAFKA
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-headless:9092}   # the bootstrap servers for KAFKA
  group-id: error
  maxRetries: 10                                                # the group identifier to use for KAFKA publishers  
  poll-timeout: 3000
  producer-retries: 10
  topic:
    errors: t-pdgs-errors

# MongoDB
mongodb:
  host: ${mongo_db_host:localhost}
  port: ${mongo_db_port:27017}
  database: ${mongo_db_database:s1pdgs}                                                                   #
