kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: webdav
    protocol: TCP
    port: 80
  - name: webdavtls
    protocol: TCP
    port: 443