spring:
  application:
    name: s1pdgs-scaler
    
# Logging
logging:
  config: log4j2.yml
  
# Kafka
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers}
  client-id: spdgs-scaler
  request-timeout-ms: 5000
  session-timeout-ms: 5000
  cnx-max-idl-ms: 660000
  topics:
    l1-jobs: ${kafka_topic_l1_jobs}
  group-id-per-topic:
    l1-jobs: l1-wrappers
    
# K8S
k8s:
  master-url: ${k8s_master-url}
  namespace: ${k8s_namespace}
  username: $k8s_username}
  client-key: ${k8s_client-key}
  client-cert-data: ${k8s_client-cert-data}

wrapper:
  label-wrapper-config:
    label: wrapperconfig
    value: l1
  label-wrapper-state-unused:
    label: wrapperstate
    value: unused
  label-wrapper-state-used:
    label: wrapperstate
    value: used
  label-wrapper-app:
    label: app
    value: l1-wrapper
  nb-pooling-pods: 3
  nb-pods-per-server: 1
  pod-template-file: /app/config/template_l1_wrapper_pod.yml
  nb-min-servers: 3
  nb-max-servers: 15
  execution-time:
    average-s: 900
    min-threshold-s: 900.0
    max-threshold-s: 1800.0
  tempo-pooling-ms: 420000
  tempo-integrity-volumeserver-ms: 21600000
  tempo-scaling-s: 600
  tempo-initial-delay-ms: 500
  tempo-delete-resources-s: 600
  wait-pod-deletion-ms: 10000
  rest-api:
    port: 8080
    nb-retry: 3
    tempo-retry-ms : 1000

# Openstack
openstack:
  server:
    endpoint: ${os_endpoint}
    domain-id: ${os_domain-id}
    project-id: ${os_project-id}
    credential-username: ${os_credential-username}
    credential-password: ${os_credential-password}
    server-wrapper: 
      available-zone: eu-west-0b
      prefix-name: k8s-node-w-l1
      image-ref: 79a60603-11be-4183-83ab-21197977253e
      boot-device-name: /dev/vda
      flavor: s1.2xlarge
      float-activation: true
      floating-network: 0a2228f2-7f8a-45f1-8e09-9039e1d09975
      key-security: viv_k8s
      networks: 01f954b1-0290-4bb4-9ee6-9ef46c2983fb
      security-groups: k8s_secgroup
      bootable-on-volume: true
    volume-wrapper:
      prefix-name: k8s-volume-l1
      description: "Bootable volume for node for wrapper L1"
      size: 128
      volume-type: SSD
      zone: eu-west-0b
  service:  
    floating-ip:
      creation:
        max-loop: 10
        tempo-loop-ms: 1000
    server:
      creation:
        max-wait-ms: 600000
      deletion:
        max-loop: 180
        tempo-loop-ms: 1000
    volume:
      creation:
        max-loop: 120
        tempo-loop-ms: 1000

dev:
  activations: 
    pod-deletion: true
    kafka-monitoring: true
    init-scaling: true
    k8s-monitoring: true
    value-monitored: true
    scaling: true
    unused-ressources-deletion: true

persistence:
  host-uri-catalog: http://app-catalog-svc:8080
  max-retries: 3
  tempo-retry-ms: 500
