spring:
  application:
    name: ${job_spring_appname:s1pdgs-jobgenerator}
    
# Logging
logging:
  config: ${job_logging_config:log4j2.yml}
 
metadata:
  host: ${catalog_rest_host:metadata-catalog-svc:8080}
  rest-api_nb-retry: ${job_rest-api_nb-retry:3}
  rest-api_tempo-retry-ms: ${job_rest-api_tempo-retry-ms:1000}
 
  
job-generator:
  diroftasktables: ${job_directoryoftasktables}
  maxnboftasktable: ${job_maxnumberoftasktables}
  maxnumberofjobs: ${job_maxnumberoftasktables}
  jobgenfixedrate: ${job_scheduledfixedrate:500}
  waitprimarycheck:
    tempo: ${job_waitprimarycheck_tempo:30000}
    retries: ${job_waitprimarycheck_retries:50}
  waitmetadatainput:
    tempo: ${job_waitmetadatainput_tempo:60000}
    retries: ${job_waitmetadatainput_retries:300}
  defaultfamily: ${products_default-family}
  outputfamiliesstr: ${products_family-per-type}
  typeoverlapstr: ${products_overlap-per-acq}
  typeslicelenstr: ${products_slice-length-per-acq}
  map-type-meta-str: ${products_link-producttype-metadataindex}
    
status:
  delete-fixed-delay-ms: ${job_status_delete-fixed-delay-ms:3000}
  max-error-counter-processing: ${job_status_max-error-counter-processing:3}
  max-error-counter-mqi: ${job_status_max-error-counter-mqi:30}

process:
  level: ${job_process_level}
  hostname: ${HOSTNAME}
  mode: ${job_process_mode:PROD}
  paramstr: ${job_process_params:Processing_Mode:NRT||Timeout:300}
  loglevelstdout: ${job_process_loglevelstdout:INFO}
  loglevelstderr: ${job_process_loglevelstderr:INFO}
  processingstation: ${job_process_processingstation:WILE}
  outputregexpstr: ${job_process_outputregexps:SM_RAW__0S:^S1[A-B]_S[1-6]_RAW__0S.*$||AN_RAW__0S:^S1[A-B]_N[1-6]_RAW__0S.*$||ZS_RAW__0S:^S1[A-B]_Z[1-6]_RAW__0S.*$||REP_L0PSA_:^S1[A|B|_]_OPER_REP_ACQ.*$||REP_EFEP_:^S1[A|B|_]_OPER_REP_PASS.*.EOF$}
  mqi:
    host-uri: ${job_process_mqi_host-uri:http://localhost:8081}
    max-retries: ${job_process_mqi_max-retries:3}
    tempo-retry-ms: ${job_process_mqi_tempo-retry:1000}
  appcatalog:
    host-uri: ${job_process_appcatalog_host-uri:http://app-catalog-svc:8080}
    max-retries: ${job_process_appcatalog_max-retries:3}
    tempo-retry-ms: ${job_process_appcatalog_tempo-retry:1000}
    tm-connect-ms: ${job_process_appcatalog_tm-connect-ms:5000}
  fixed-delay-ms: ${job_process_fixed-delay-ms:200}
    
level0:
  maxnumberofsessions: ${l0_maxnumberofsessions:20}
  maxagesession: ${l0_maxagesession:25200000}
  dir-extractor-sessions: ${l0_dir-extractor-sessions:/data/sessions/}
  
level1:
  pathroutingxmlfile: ${l1_pathroutingxmlfile:/data/config/l1_config/routing.xml}
  
pattern-l0-slices:
  regexp: ${pattern-l0-slices_regexp:^([0-9a-z]{2})([0-9a-z]){1}_(([0-9a-z]{2})_RAW__0([0-9a-z_]{3}))_([0-9a-z]{15})_([0-9a-z]{15})_([0-9a-z_]{6})\\w{1,}\\.SAFE(/.*)?$}
  m-group-sat-id: ${pattern-l0-slices_placeMatchSatelliteId:2}
  m-group-mission-id: ${pattern-l0-slices_placeMatchMissionId:1}
  m-group-acquisition: ${pattern-l0-slices_placeMatchAcquisition:4}
  m-group-start-time: ${pattern-l0-slices_placeMatchStartTime:6}
  m-group-stop-time: ${pattern-l0-slices_placeMatchStopTime:7}
