#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-metadata-catalog
  profiles:
    active: prod
    
# Logging
logging:
  config: ${catalog_logging_config:logback-spring.xml}
  level:
    ROOT: ${catalog_logging_level_root:ERROR}
    org.springframework: ${catalog_logging_level_orgspringframework:ERROR}
    fr.viveris.s1pdgs: ${catalog_logging_level_frviveriss1pdgs:INFO}
    kafka: ${catalog_logging_level_kafka:WARN}
    org.apache: ${catalog_logging_level_orgapache:WARN}
  file: ${catalog_logging_file:./s1pdgs-metadata-catalog.log}

# KAFKA
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-svc:9093}
  group-id: ${catalog_kafka_group:metadata-catalog}
  poll-timeout: ${kafka_poll-timeout:500}
  topic:
    metadata: ${kafka_topic_metadata:t-pdgs-metadata}
    
# Elastic Search
elasticsearch:
  host: ${elastic_host:es-svc}
  port: ${elastic_port:25000}
  index-type: ${elastic_index-type:metadata}


#Object Storage
storage:
  user:
    id: MEF5PCBPTXHKOUTCKW3G
    secret: 4YiRYBN6HulfbA6uP7eZdhlm9Jb5JVYm18byMGJo
  endpoint: http://oss.eu-west-0.prod-cloud-ocb.orange-business.com/
  region: eu-west-0
  buckets:
    config-files: config-files
    session-files: session-files
