spring:
  application:
    name: ${job_spring_appname:s1pdgs-jobgenerator}
    
# Logging
logging:
  config: log4j2.yml
 
metadata:
  host: ${catalog_rest_host:metadata-catalog-svc:8080}
  rest-api_nb-retry: 3
  rest-api_tempo-retry-ms: 1000
  
job-generator:
  diroftasktables: /app/l0_config/task_tables/
  maxnboftasktable: 1
  jobgenfixedrate: 100
  waitprimarycheck:
    tempo: 30000
  waitmetadatainput:
    tempo: 60000
  defaultfamily: BLANK
  outputfamiliesstr: ${products_family-per-type}
  type-overlap:
    EW: 8.2F
    IW: 7.4F
    SM: 7.7F
    WM: 0.0F
  type-slice-length:
    EW: 60.0F
    IW: 25.0F
    SM: 25.0F
    WM: 0.0F
  map-type-meta: 
    AUX_RES: AUX_RESORB
    
status:
  delete-fixed-delay-ms: 1800000
  max-error-counter-processing: 3
  max-error-counter-mqi: 30

process:
  level: ${job_process_level}
  hostname: ${HOSTNAME}
  mode: PROD
  params: 
    Processing_Mode: NRT
    Timeout: 300
  loglevelstdout: INFO
  loglevelstderr: INFO
  processingstation: WILE
  outputregexps: 
    SM_RAW__0S: ^S1[A-B]_S[1-6]_RAW__0S.*$
    AN_RAW__0S: ^S1[A-B]_N[1-6]_RAW__0S.*$
    ZS_RAW__0S: ^S1[A-B]_Z[1-6]_RAW__0S.*$
    REP_L0PSA_: ^S1[A|B|_]_OPER_REP_ACQ.*$
    REP_EFEP_: ^S1[A|B|_]_OPER_REP_PASS.*.EOF$
  mqi:
    host-uri: http://localhost:8081
    max-retries: 3
    tempo-retry-ms: 1000
  appcatalog:
    host-uri: http://app-catalog-svc:8080
    max-retries: 3
    tempo-retry-ms: 1000
    tm-connect-ms: 5000
  fixed-delay-ms: 200
  initial-delay-ms: 5000
    
level0:
  dir-extractor-sessions: /data/sessions/
  
level1:
  pathroutingxmlfile: /app/l1_config/routing.xml
  
pattern-l0-slices:
  regexp: ${pattern-l0-slices_regexp:^([0-9a-z]{2})([0-9a-z]){1}_(([0-9a-z]{2})_RAW__0([0-9a-z_]{3}))_([0-9a-z]{15})_([0-9a-z]{15})_([0-9a-z_]{6})\\w{1,}\\.SAFE(/.*)?$}
  m-group-sat-id: ${pattern-l0-slices_placeMatchSatelliteId:2}
  m-group-mission-id: ${pattern-l0-slices_placeMatchMissionId:1}
  m-group-acquisition: ${pattern-l0-slices_placeMatchAcquisition:4}
  m-group-start-time: ${pattern-l0-slices_placeMatchStartTime:6}
  m-group-stop-time: ${pattern-l0-slices_placeMatchStopTime:7}
