spring:
  application:
    name: csgrs-native-api

# Logging
logging:
  level:
    root: ERROR
    de.werum.csgrs: DEBUG
    org.springframework: INFO
    org.apache: INFO

# Native API config
native-api:
  # version
  version: v1

# REST controller
server:
  port: 8080
