#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-metadata-catalog
    
# Logging
logging:
  config: ${catalog_logging_config:log4j2.yml}
    
# Elastic Search
elasticsearch:
  host: ${elastic_host:es-svc}
  port: ${elastic_port:25000}
  index-type: ${elastic_index-type:metadata}
  connect-timeout-ms: ${elastic_connect_timeout_ms:2000}
  socket-timeout-ms: ${elastic_socket_timeout_ms:10000}
  max-retry-timeout-ms: ${elastic_max_retry_timeout_ms:30000}
    
# File
file:
  file-with-manifest-ext: ${catalog_file-with-manifest-ext:.safe}
  manifest-filename: ${catalog_manifest-filename:manifest.safe}
  mqi:
    host-uri: ${catalog_mqi_host-uri:http://localhost:8081}
    max-retries: ${catalog_mqi_max-retries:3}
    tempo-retry-ms: ${catalog_mqi_tempo-retry-ms:1000}
  product-categories:
    auxiliary-files:
      local-directory: ${catalog_auxiliary-files_local-directory:/data/local-catalog/auxiliary_files/} # Must contains the last /
      fixed-delay-ms: ${catalog_auxiliary-files_fixed-delay-ms:500}
      init-delay-poll-ms: ${catalog_auxiliary-files_init-delay-poll-ms:2000}
    edrs-sessions:
      local-directory: ${catalog_edrs-sessions_local-directory:/data/local-catalog/edrs_sessions/} # Must contains the last /
      fixed-delay-ms: ${catalog_edrs-sessions_fixed-delay-ms:500}
      init-delay-poll-ms: ${catalog_edrs-sessions_init-delay-poll-ms:2000}
    level-products:
      local-directory: ${catalog_level-products_local-directory:/data/local-catalog/level_products/} # Must contains the last /
      fixed-delay-ms: ${catalog_level-products_fixed-delay-ms:500}
      init-delay-poll-ms: ${catalog_level-products_init-delay-poll-ms:2000}
    
# REST controller
server:
  port: ${catalog_rest_server_port:8080}
  
# Metadata Extractor
mdextractor:
  typeoverlapstr: ${products_overlap-per-acq}
  typeslicelengthstr: ${products_slice-length-per-acq}
  xslt-directory: ${catalog_xslt-directory:xsltDir/} # Must contains the last /
  
status:
  max-error-counter: ${catalog_status_max-error-counter:3}