#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-ingestor
  profiles:
    active: prod
    
# Logging
logging:
  config: ${ingestor_logging_config:logback-spring.xml}
  level:
    ROOT: ${ingestor_logging_level_root:ERROR}
    org.springframework: ${ingestor_logging_level_orgspringframework:ERROR}
    fr.viveris.s1pdgs: ${ingestor_logging_level_frviveriss1pdgs:INFO}
    kafka: ${ingestor_logging_level_kafka:WARN}
  file: ${ingestor_logging_file:./s1pdgs-ingestor.log}

# KAFKA
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-svc:9093}
  group-id: ${ingestor_kafka_group:metadata-catalog}
  poll-timeout: ${kafka_poll-timeout:500}
  topic:
    config-files: ${kafka_topic_config_files:t-pdgs-config-files}
    edrs-sessions: ${kafka_topic_edrs_sessions:t-pdgs-edrs-sessions}

#FTP
ftp:
  host: input-ftpserver-svc
  port: 21
  username: user
  password: passwd
  client-mode: 2
  local-directory: /data/local-ingestor/
  command-options:
    mget: -P -R -D
  config-files:
    remote-directory: /config_files/
    upload-fixed-rate: 3000
    cache-max-capacity: 10
  session-files:
    remote-directory: /edrs_sessions/
    upload-fixed-rate: 5000
    cache-max-capacity: 70

#Object Storage
storage:
  user:
    id: ${storage_user_id:MEF5PCBPTXHKOUTCKW3G}
    secret: ${storage_user_secret:4YiRYBN6HulfbA6uP7eZdhlm9Jb5JVYm18byMGJo}
  endpoint: ${storage_endpoint:http://oss.eu-west-0.prod-cloud-ocb.orange-business.com/}
  region: ${storage_region:eu-west-0}
  buckets:
    config-files: ${storage_buckets_config-files:config-files}
    session-files: ${storage_buckets_session-files:session-files}
 
 
# File
file:
  config-files:
    local-directory: ${ingestor_config-files_local-directory:/data/local-ingestor/config_files/} # Must contains the last /
    read-fixed-rate: ${ingestor_file_read-fixed-rate:1000}
    clean-empty-directory-rate: ${ingestor_file_clean-empty-directory-rate:15000}
    clean-empty-min-age: ${ingestor_file_clean-empty-min-age:13000}
    cache-max-capacity: ${ingestor_config-files_cache-max-capacity:10}
  session-files:
    local-directory: ${ingestor_session-files_local-directory:/data/local-ingestor/edrs_sessions/} # Must contains the last /
    read-fixed-rate: ${ingestor_file_read-fixed-rate:1000}
    clean-empty-directory-rate: ${ingestor_file_clean-empty-directory-rate:15000}
    clean-empty-min-age: ${ingestor_file_clean-empty-min-age:13000}
    cache-max-capacity: ${ingestor_session-files_cache-max-capacity:70}
