spring:
  application:
    name: s1pdgs-wrapper-app
    
logging:
  config: ${wrapper_logging_config:log4j2.yml}
    
# REST controller
server:
  port: ${wrapper_rest_server_port:8080}
    
process:
  level: ${wrapper_process_level}
  fixed-delay-ms: ${wrapper_process_fixed-delay:500}
  init-delay-poll-ms: ${wrapper_process_poll-ms:1000}
  tm-proc-one-task-s: ${wrapper_process_timeout-process-one-task-s:600}
  tm-proc-all-tasks-s: ${wrapper_process_timeout-process-all-tasks-s:1800}
  tm-proc-stop-s: ${wrapper_process_timeout-process-stop-s:300}
  tm-proc-check-stop-s: ${wrapper_process_timeout-process-check-stop-s:60}
  size-batch-upload:  ${wrapper_process_size-batch-s3-upload:10}
  size-batch-download: ${wrapper_process_size-batch-s3-download:10}
  wap-nb-max-loop: ${wrapper_process_wait-active-process-nb-max-loop:12}
  wap-tempo-s: ${wrapper_process_wait-active-process-tempo-s:10}
  mqi:
    host-uri: ${wrapper_process_mqi_host-uri:http://localhost:8081}
    max-retries: ${wrapper_process_mqi_max-retries:3}
    tempo-retry-ms: ${wrapper_process_mqi_tempo-retry:1000}

status:
  delete-fixed-delay-ms: ${wrapper_status_delete-fixed-delay-ms:3000}
  max-error-counter: ${wrapper_status_max-error-counter:3}

dev:
  steps-activation:
    download: ${wrapper_process_dev-steps-activation_download:true}
    upload: ${wrapper_process_dev-steps-activation_upload:true}
    erasing: ${wrapper_process_dev-steps-activation_erasing:true}