#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-metadata-catalog
  profiles:
    active: prod
    
# Logging
logging:
  config: logback-spring.xml
  level:
    ROOT: ERROR
    org.springframework: WARN
    fr.viveris.s1pdgs: DEBUG
    kafka: WARN
    org.apache: WARN
  file: ./s1pdgs-metadata-catalog.log

#Object Storage
storage:
  user:
    id: MEF5PCBPTXHKOUTCKW3G
    secret: 4YiRYBN6HulfbA6uP7eZdhlm9Jb5JVYm18byMGJo
  endpoint: http://oss.eu-west-0.prod-cloud-ocb.orange-business.com/
  region: eu-west-0
  buckets:
    config-files: config-files
    session-files: session-files

# KAFKA
kafka:
  bootstrap-servers: 172.17.50.10:9092
  group-id: metadata-catalog
  poll-timeout: 500
  topic:
    metadata: t-pdgs-metadata
    
# Elastic Search
elasticsearch:
  host: es-svc
  port: 25000
  index-type: metadata