spring:
  application:
    name: s1pdgs-mqi-app
    
logging:
  config: ${mqi_log2j_file:log4j2.yml}
  
# Kafka
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-svc:9093}
  hostname: ${HOSTNAME}
  client-id: ${HOSTNAME}
  error-topic: ${kafka_topic_errors:t-pdgs-errors}
  consumer:
    group-id: ${mqi_kafka_consumer_group:l0-wrappers}
    max-poll-records: ${mqi_kafka_consumer_max-poll-records:1}
    max-poll-interval-ms: ${mqi_kafka_consumer_max-poll-interval-ms:3600000}
    heartbeat-intv-ms: ${mqi_kafka_consumer_heartbeat-interval-ms:3000}
    session-timeout-ms: ${mqi_kafka_consumer_session-timeout-ms:10000}
    auto-offset-reset: ${mqi_kafka_consumer_auto-offset-reset:latest}
    offset-dft-mode: ${mqi_kafka_consumer_offset-dft-mode:-3}
  listener:
    poll-timeout-ms: ${mqi_kafka_listener_poll-timeout-ms:500}
  producer:
    max-retries: ${mqi_kafka_producer_max-retries:5}
    
# Configuration per categories of products
application:
  hostname: ${HOSTNAME}
  max-error-counter: ${mqi_app_max-error-counter:3}
  stop-fixed-delay-ms: ${mqi_app_stop-fixed-delay-ms:3000}
  wait-next-ms: ${mqi_app_wait-next-ms:1000}
  product-categories:
    auxiliary-files:
      consumption:
        enable: ${mqi_auxiliary-files_consumption_enable:false}
        topics-with-priority: ${mqi_auxiliary-files_consumption_topics}
      publication:
        enable: ${mqi_auxiliary-files_publication_enable:false}
        routing-file: ${mqi_auxiliary-files_publication_routing-file:routing-files/auxiliary-files.xml}
    edrs-sessions:
      consumption:
        enable: ${mqi_edrs-sessions_consumption_enable:false}
        topics-with-priority: ${mqi_edrs-sessions_consumption_topics}
      publication:
        enable: ${mqi_edrs-sessions_publication_enable:false}
        routing-file: ${mqi_edrs-sessions_publication_routing-file:routing-files/edrs-sessions.xml}
    level-products:
      consumption:
        enable: ${mqi_level-products_consumption_enable:false}
        topics-with-priority: ${mqi_level-products_consumption_topics}
      publication:
        enable: ${mqi_level-products_publication_enable:false}
        routing-file: ${mqi_level-products_publication_routing-file:routing-files/level-products.xml}
    level-reports:
      consumption:
        enable: ${mqi_level-reports_consumption_enable:false}
        topics-with-priority: ${mqi_level-reports_consumption_topics}
      publication:
        enable: ${mqi_level-reports_publication_enable:false}
        routing-file: ${mqi_level-reports_publication_routing-file:routing-files/level-reports.xml}
    level-jobs:
      consumption:
        enable: ${mqi_level-jobs_consumption_enable:false}
        topics-with-priority: ${mqi_level-jobs_consumption_topics}
      publication:
        enable: ${mqi_level-jobs_publication_enable:false}
        routing-file: ${mqi_level-jobs_publication_routing-file:routing-files/level-jobs.xml}
    
# REST controller
server:
  port: ${mqi_rest_server_port:8081}
  
# App catlog
persistence:
  host-uri-catalog: ${mqi_persistence_host-uri-catalog:http://app-catalog-svc:8080}
  port-uri-other-app: ${mqi_persistence_port-uri-other-app:8080}
  max-retries: ${mqi_persistence_max-retries:3}
  tempo-retry-ms: ${mqi_persistence_tempo-retry-ms:500}
  other-app:
    suffix-uri: ${mqi_persistence_other-app_suffix-uri:.l1-wrapper-svc}