#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-ingestor
  profiles:
    active: ${ingestor_spring_profile:prod}
    
# Logging
logging:
  config: ${ingestor_logging_config:logback-spring.xml}
  level:
    ROOT: ${ingestor_logging_level_root:ERROR}
    org.springframework: ${ingestor_logging_level_orgspringframework:ERROR}
    fr.viveris.s1pdgs: ${ingestor_logging_level_frviveriss1pdgs:INFO}
    kafka: ${ingestor_logging_level_kafka:WARN}
  file: ${ingestor_logging_file:./s1pdgs-ingestor.log}

# KAFKA
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-svc:9093}
  group-id: ${ingestor_kafka_group:ingestors}
  poll-timeout: ${ingestor_kafka_poll-timeout:500}
  topic:
    auxiliary-files: ${kafka_topic_auxiliary_files:t-pdgs-auxiliary-files}
    edrs-sessions: ${kafka_topic_edrs_sessions:t-pdgs-edrs-sessions}

#FTP
ftp:
  host: ${input_ftp_pasv_address:input-ftpserver-svc}
  port: 21
  username: ${input_ftp_user:user}
  password: ${input_ftp_pass:passwd}
  client-mode: 2
  local-directory: /data/local-ingestor/
  command-options:
    mget: -P -R -D
  auxiliary-files:
    remote-directory: /auxiliary_files/
    upload-fixed-rate: 3000
    cache-max-capacity: 10
  session-files:
    remote-directory: /edrs_sessions/
    upload-fixed-rate: 5000
    cache-max-capacity: 70

#Object Storage
storage:
  user:
    id: ${storage_user_id}
    secret: ${storage_user_secret}
  endpoint: ${storage_endpoint}
  region: ${storage_region}
  buckets:
    auxiliary-files: ${storage_buckets_auxiliary-files:auxiliary-files}
    session-files: ${storage_buckets_session-files:session-files}
 
 
# File
file:
  auxiliary-files:
    local-directory: ${ingestor_auxiliary-files_local-directory:/data/local-ingestor/auxiliary_files/} # Must contains the last /
    read-fixed-rate: ${ingestor_config-file_read-fixed-rate:1000}
    clean-empty-directory-rate: ${ingestor_config-file_clean-empty-directory-rate:15000}
    clean-empty-min-age: ${ingestor_config-file_clean-empty-min-age:13000}
    cache-max-capacity: ${ingestor_auxiliary-files_cache-max-capacity:10}
  session-files:
    local-directory: ${ingestor_session-files_local-directory:/data/local-ingestor/edrs_sessions/} # Must contains the last /
    read-fixed-rate: ${ingestor_session-file_read-fixed-rate:1000}
    clean-empty-directory-rate: ${ingestor_session-file_clean-empty-directory-rate:15000}
    clean-empty-min-age: ${ingestor_session-file_clean-empty-min-age:13000}
    cache-max-capacity: ${ingestor_session-files_cache-max-capacity:70}
