spring:
  application:
    name: ${job_spring_appname:s1pdgs-jobgenerator}
    
# Logging
logging:
  config: ${job_logging_config:log4j2.yml}
 
metadata:
  host: ${catalog_rest_host:metadata-catalog-svc:8080}
  
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-svc:9093}
  group-id: ${job_kafka_group:jobgenerators}
  client-id: ${job_kafka_client:job-generator}
  poll-timeout: ${job_kafka_poll-timeout:500}
  topics:
    edrs-sessions: ${kafka_topic_edrs_sessions:t-pdgs-edrs-sessions}
    l0-slices: ${kafka_topic_l0_slices:t-pdgs-l0-slices}
    lx-jobs: ${job_kafka_topic_lx_jobs}
  enable-consumer:
    edrs-sessions: ${job_kafka_enable-consumer_edrs-sessions:true}
    l0-slices: ${job_kafka_enable-consumer_l0-slices:false}
    
storage:
  user:
    id: ${storage_user_id}
    secret: ${storage_user_secret}
  endpoint: ${storage_endpoint}
  region: ${storage_region}
  buckets:
    edrs-sessions: ${storage_buckets_session-files:session-files}
  
job-generator:
  directoryoftasktables: ${job_directoryoftasktables}
  maxnumberoftasktables: ${job_maxnumberoftasktables:2}
  maxnumberofjobs: ${job_maxnumberoftasktables:40}
  scheduledfixedrate: ${job_scheduledfixedrate:500}
  waitprimarycheck:
    tempo: ${job_waitprimarycheck_tempo:2000}
    retries: ${job_waitprimarycheck_retries:2}
  waitmetadatainput:
    tempo: ${job_waitmetadatainput_tempo:60000}
    retries: ${job_waitmetadatainput_retries:300}
  defaultoutputfamily: ${products_default-family}
  outputfamiliesstr: ${products_family-per-type}
  typeoverlapstr: ${products_overlap-per-acq}
  typeslicelengthstr: ${products_slice-length-per-acq}
  link-producttype-metadataindex-str: ${products_link-producttype-metadataindex}
    
    
process:
  level: ${job_process_level}
  paramstr: ${job_process_params}
  loglevelstdout: ${job_process_loglevelstdout:INFO}
  loglevelstderr: ${job_process_loglevelstderr:INFO}
  processingstation: ${job_process_processingstation}
  outputregexpstr: ${job_process_outputregexps}
    
level0:
  maxnumberofsessions: ${l0_maxnumberofsessions:20}
  maxagesession: ${l0_maxagesession:25200000}
  dir-extractor-sessions: ${l0_dir-extractor-sessions:/data/sessions/}
  
level1:
  pathroutingxmlfile: ${l1_pathroutingxmlfile}
  
pattern-l0-slices:
  regexp: ${pattern-l0-slices_regexp:^([0-9a-z]{2})([0-9a-z]){1}_(([0-9a-z]{2})_RAW__0([0-9a-z_]{3}))_([0-9a-z]{15})_([0-9a-z]{15})_([0-9a-z_]{6})\\w{1,}\\.SAFE(/.*)?$}
  placeMatchSatelliteId: ${pattern-l0-slices_placeMatchSatelliteId:2}
  placeMatchMissionId: ${pattern-l0-slices_placeMatchMissionId:1}
  placeMatchAcquisition: ${pattern-l0-slices_placeMatchAcquisition:4}
  placeMatchStartTime: ${pattern-l0-slices_placeMatchStartTime:6}
  placeMatchStopTime: ${pattern-l0-slices_placeMatchStopTime:7}
