#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-ingestor
    
# Logging
logging:
  config: ${ingestor_logging_config:log4j2.yml}

# KAFKA
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-svc:9093}
  group-id: ${ingestor_kafka_group:ingestors}
  poll-timeout: ${ingestor_kafka_poll-timeout:500}
  topic:
    auxiliary-files: ${kafka_topic_auxiliary_files:t-pdgs-auxiliary-files}
    edrs-sessions: ${kafka_topic_edrs_sessions:t-pdgs-edrs-sessions}

#Object Storage
storage:
  user:
    id: ${storage_user_id}
    secret: ${storage_user_secret}
  endpoint: ${storage_endpoint}
  region: ${storage_region}
  buckets:
    auxiliary-files: ${storage_buckets_auxiliary-files:auxiliary-files}
    session-files: ${storage_buckets_session-files:session-files}
 
 
# File
file:
  auxiliary-files:
    local-directory: ${ingestor_auxiliary-files_local-directory:/data/local-ingestor/auxiliary_files/} # Must contains the last /
    read-fixed-rate: ${ingestor_config-file_read-fixed-rate:1000}
    poll-fixed-delay: 1000
    max-msg-per-poll: 5
    executor-pool-size: 5
    clean-empty-directory-rate: ${ingestor_config-file_clean-empty-directory-rate:15000}
    clean-empty-min-age: ${ingestor_config-file_clean-empty-min-age:13000}
    cache-max-capacity: ${ingestor_auxiliary-files_cache-max-capacity:10}
  session-files:
    local-directory: ${ingestor_session-files_local-directory:/data/local-ingestor/edrs_sessions/} # Must contains the last /
    read-fixed-rate: ${ingestor_session-file_read-fixed-rate:1000}
    poll-fixed-delay: 1000
    max-msg-per-poll: 5
    executor-pool-size: 5
    clean-empty-directory-rate: ${ingestor_session-file_clean-empty-directory-rate:15000}
    clean-empty-min-age: ${ingestor_session-file_clean-empty-min-age:13000}
    cache-max-capacity: ${ingestor_session-files_cache-max-capacity:70}
