#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: s1pdgs-applicative-catalog
    
# Logging
logging:
  config: ${appcatalog_logging_config:log4j2.yml}
  
# MongoDB
mongodb:
  host: ${mongo_db_host:mongodb-2.mongodb-svc}
  port: ${mongo_db_port:27017}
  database: ${mongo_db_database:s1pdgs}
  old-entry-ms: ${appcatalog_mongodb_old_entry_ms:86400000}
  clean-cron: ${appcatalog_mongodb_clean_cron:0 0 0 * * *}
  
#MQI
mqi:
  max-retries: ${appcatalog_mqi_max_retries:3}