openapi: 3.0.1
info:
  title: RS Native API
  description: The API of the Reference System that can be used to query product data.
  version: "1.0"
servers:
- url: http://localhost:8888
  description: Generated server url
tags:
- name: Metadata
paths:
  /api/v1/ping:
    get:
      tags:
      - Metadata
      summary: check whether the API service is reachable and running and retrieve
        the API version number
      description: A HTTP 200 answer is to be expected when the API service is running
        and reachable. Additionally the current API version number will be retrieved.
      operationId: PingApi
      responses:
        "500":
          description: Internal Server Error - the API service encountered an unexpected
            condition that prevented it from fulfilling the request
          content: {}
        "400":
          description: "Bad Request - the API service rejects to process the request\
            \ because of client side errors, for example a malformed request syntax"
        "200":
          description: OK - the API service is running and reachable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
  /api/v1/missions:
    get:
      tags:
      - Metadata
      summary: retrieve the names of the missions supported by the API
      description: To search for satellite product data the data can be filtered by
        attributes which depend on the product type which in turn depend on the satellite
        mission. This endpoint returns all names of the missions supported by the
        API.
      operationId: GetMissions
      responses:
        "500":
          description: Internal Server Error - the API service encountered an unexpected
            condition that prevented it from fulfilling the request
          content: {}
        "200":
          description: OK - the supperted mission names were returned with this response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Missions'
        "400":
          description: "Bad Request - the API service rejects to process the request\
            \ because of client side errors, for example a malformed request syntax"
  /api/v1/missions/{missionName}/productTypes:
    get:
      tags:
      - Metadata
      summary: retrieve the names of the product types supported for a particular
        mission
      description: To search for satellite product data the data can be filtered by
        attributes which depend on the product type which in turn depend on the satellite
        mission. This endpoint returns all names of the product types supported for
        the given mission.
      operationId: GetProductTypes
      parameters:
      - name: missionName
        in: path
        required: true
        schema:
          type: string
      responses:
        "500":
          description: Internal Server Error - the API service encountered an unexpected
            condition that prevented it from fulfilling the request
          content: {}
        "200":
          description: OK - the product type names for the given mission were returned
            with this response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductTypes'
        "400":
          description: "Bad Request - the API service rejects to process the request\
            \ because of client side errors, for example a malformed request syntax"
  /api/v1/missions/{missionName}/productTypes/{productType}/attributes:
    get:
      tags:
      - Metadata
      summary: retrieve the names of the attributes supported for a particular mission
        and product type
      description: To search for satellite product data the data can be filtered by
        attributes which depend on the product type which in turn depend on the satellite
        mission. This endpoint returns all attribute names supported for the given
        mission and product type.
      operationId: GetAttributes
      parameters:
      - name: missionName
        in: path
        required: true
        schema:
          type: string
      - name: productType
        in: path
        required: true
        schema:
          type: string
      responses:
        "500":
          description: Internal Server Error - the API service encountered an unexpected
            condition that prevented it from fulfilling the request
          content: {}
        "400":
          description: "Bad Request - the API service rejects to process the request\
            \ because of client side errors, for example a malformed request syntax"
        "200":
          description: OK - the attribute names for the given mission and product
            type were returned with this response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attributes'
components:
  schemas:
    PingResponse:
      type: object
      properties:
        apiVersion:
          type: string
          description: the version of the API
          example: "1.0"
    Missions:
      type: object
      properties:
        missions:
          type: array
          description: the names of the missions supported by the API
          example:
          - s1
          - s2
          - s3
          items:
            type: string
            description: the names of the missions supported by the API
            example: "[\"s1\",\"s2\",\"s3\"]"
    ProductTypes:
      type: object
      properties:
        productTypes:
          type: array
          description: the names of the product types for a particular mission
          example:
          - l1
          - l2
          - aux-safe
          items:
            type: string
            description: the names of the product types for a particular mission
            example: "[\"l1\",\"l2\",\"aux-safe\"]"
    Attributes:
      type: object
      properties:
        attributes:
          type: array
          description: the attribute names for a particular mission and product type
          example:
          - attr_beginningDateTime_date
          - attr_orbitDirection_string
          - attr_sliceNumber_long
          items:
            type: string
            description: the attribute names for a particular mission and product
              type
            example: "[\"attr_beginningDateTime_date\",\"attr_orbitDirection_string\"\
              ,\"attr_sliceNumber_long\"]"
