spring:
  main:
    banner-mode: "off"
  application:
    name: s1pdgs-data-request-worker
 
# Logging
logging:
  config: ${log4j_config:log/log4j2.yml}

process:
  hostname: ${HOSTNAME}                                          # Hostname

server:
  port: 8080

# Kafka config
kafka:
  # host:port to use for establishing the initial connection to the Kafka cluster
  bootstrap-servers: ${kafka_bootstrap-servers}
  # Hostname
  hostname: ${HOSTNAME}
  # Topic name for the errors
  error-topic: ${kafka_topic_errors}
  # Kafka Producer config
  producer:
    # When greater than zero, enables retrying of failed sends
    max-retries: 10

# MQI config
mqi:
  # The host and port for querying MQI server
  host-uri: http://localhost:8081
  # The maximal number of consecutive retries following a MQI request error, default is 3
  max-retries: 100
  # Time between retries in milliseconds, default is 1000
  tempo-retry-ms: 2000

# Application status configuration
status:
  # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not, default is 3000
  delete-fixed-delay-ms: 3000
  # The number of consecutive processing errors leading to the state FATALERROR, default is 100
  max-error-counter-processing: 3
  # The number of consecutive MQI errors leading to the state FATALERROR, default is 100
  max-error-counter-mqi: 30

# Data Request Worker config
data-request-worker:
  # Hostname
  hostname: ${HOSTNAME}
  # Polling interval for MQI messages in millis, default is 1000
  polling-interval-ms: 1000
  # Initial waiting time before polling MQI in millis
  polling-initial-delay-ms: 5000

