# Copyright 2023 Airbus
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  main:
    banner-mode: "off"
  application:
    name: {{ .Values.service.name }}
 
# Logging
logging:
  config: {{ .Values.logConfig }}
  
# Metadata Search Controller
metadata:
  host: {{ .Values.metadata.host }}
  rest-api_nb-retry: {{ .Values.metadata.restApiNbRetry }}
  rest-api_tempo-retry-ms: {{ .Values.metadata.restApiTempoRetryMs }}
  
# Elastic Search
elasticsearch:
  # Host of Elasticsearch cluster
  host: {{ .Values.elasticsearch.host }}
  # Port of Elasticsearch cluster                                
  port: {{ .Values.elasticsearch.port }}
  # Timeout in milliseconds of connection to the cluster                                        
  connect-timeout-ms: {{ .Values.elasticsearch.timeout.connection }}
  # Timeout in milliseconds of the socket to the cluster                        
  socket-timeout-ms: {{ .Values.elasticsearch.timeout.socket }}
  # limitation of Elastic search results
  search-result-limit: {{ .Values.elasticsearch.searchResultLimit }}

process:
  hostname: ${HOSTNAME}

server:
  port: {{ .Values.service.port }}

eviction-management-worker:
  eviction-interval-ms: {{ .Values.worker.evictionIntervalMs }}
  
# Generated from obs-stream-parameters.properties
obs: {{ toYaml  .Values.obs | nindent 2 }}