before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

stages:
  - build
  - push_dev
  - push_master
  - push_tag

build:
  stage: build
  tags:
  - docker
  script:
  - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .

push_dev:
  stage: push_dev
  tags:
  - docker
  except:
    - tags
    - master
  script:
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

push_master:
  stage: push_master
  tags:
  - docker
  only:
    - master
  script:
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest

push_tag:
  stage: push_tag
  tags:
  - docker
  only:
    - tags
  script:
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_TAG $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG

