apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    plugins.konghq.com: kong-oidc-plugin-prip
  name: {{ .Release.Name }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-svc
          servicePort: 8080
        path: /odata
