# Shall helm deploy the simulator images?
simulator:
  simulateL0AioIpf: false
  simulateL0AspIpf: false
  simulateL1Ipf: false
  simulateL2Ipf: false
  simulateMbuIpf: false
  
image:
  imagePullSecrets: harbor-tools
  registry: registry.tools.s1pdgs.eu
  repository: werum/processing
  tag: develop

mqiImage:
  registry: registry.tools.s1pdgs.eu
  repository: werum/processing
  name: s1pro-core-mqi-server
  tag: develop

mqi:
  persistence:
    messagePersistenceStrategy: AppCatalogMessagePersistence # InMemoryMessagePersistence | AppCatalogMessagePersistence

gateway:
  toleration:
    key: node-role.kubernetes.io/gateway
    effect: NoSchedule
  label:
    key: node-role.kubernetes.io/gateway
    value:
      net: infra
      std: std
      edrs:
        pedc: edrs-pedc
        bedc: edrs-bedc

myocean:
  toleration:
    key: node-role.kubernetes.io/myocean
    effect: NoSchedule
  label:
    key: node-role.kubernetes.io/myocean
    value: ftp
    
qcss:
  ingestion:
    host: s1pro-mock-qcss-svc.processing.svc.cluster.local
    path: /
    port: 21
    enablePasv: true
    explicitFtps: true
    disableCertificateCheck: false
    enableHostnameVerification: false
    enableDataChannelEncryption: false
    sslProtocol: TLSv1.2
    connectTimeoutSec: 60
    directory: "ftps://${edip.host}:${edip.port}${edip.path}out/"
    keystore_data: ""
    keystore_pass: "changeit"
    truststore_data: /u3+7QAAAAIAAAABAAAAAgAIbXlvY2VhbjEAAAF3RQrFWwAFWC41MDkAAAPDMIIDvzCCAqegAwIBAgIUUbIDATMWy1AeVKX9P8A/0kaI5mEwDQYJKoZIhvcNAQELBQAwbzELMAkGA1UEBhMCREUxFTATBgNVBAgMDExvd2VyIFNheG9ueTESMBAGA1UEBwwJTHVlbmVidXJnMSEwHwYDVQQKDBhXZXJ1bSBTb2Z0d2FyZSAmIFN5c3RlbXMxEjAQBgNVBAMMCXMxcGRncy5ldTAeFw0yMDEyMDQxODQwMzhaFw0yMTEyMDQxODQwMzhaMG8xCzAJBgNVBAYTAkRFMRUwEwYDVQQIDAxMb3dlciBTYXhvbnkxEjAQBgNVBAcMCUx1ZW5lYnVyZzEhMB8GA1UECgwYV2VydW0gU29mdHdhcmUgJiBTeXN0ZW1zMRIwEAYDVQQDDAlzMXBkZ3MuZXUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZGsBDpcjrwGCY74UsujgSZkcQsRjv9TSCHimOV/dlvbDl58iIhZUg93uwub+Ae0F77pfPClN5YDjbepkT6qWWJd06AAUDlbylGELrnqNANpIiVqK2YVrOUR2qBnVDronOrrajeTD5bBAtPpjZssc5v3swhdqSLSBKTz/5LykOSvD4IpxKkdCJBu/L+y01kUGDe3eXYbbf4T1tjo11t4wJunUkv0RV2nvnPkrdu/YtTN9X7kw2LRNaHR0rHudo68F8m3PylC9HtDetK/bZ2gO23Vy5ZLriKpDi4cycqdAIUy0mBwjd3O4nQ353bh7T5l2zuPTcvysbtp9u5SbTLLLPAgMBAAGjUzBRMB0GA1UdDgQWBBRn55CvXWTHfl4RIavXecPpcM3AsDAfBgNVHSMEGDAWgBRn55CvXWTHfl4RIavXecPpcM3AsDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQDYXwNm4CnLsBXRj995oVaRuCG87F4srET7CzCrZUEy9QJYTxreB7oQz8dsFeW9SRbb5PaWhlnDwXjTIq03GUN3TIDLRcW4uEzRL/9rWv0Nl5hzdVo6GTFJ1drUTtzjtmv5laTs4gxF36R0xxl+TeYSgo41T78Fv6NIYvcABw5zdZoydbZyt2WkbWiJx8fkX5jbn+mXK3ECprhRYb6tMPUxeMRB0ZZEDrG7A+7qyLF9fpvx6m2qF80CaXKekxf4im2R7UjzqS0+b5c02JJnBpNrUvrjAabNh0Fd3omKjEGRoB5loK6c8t3rS5sr6PCr27wPLcSNT45u0P3FnsEYGnOZ5wEFmzWTWqty+5TotBFojPkkuQQ=
    truststore_pass: changeit
    bufferInputs: false
  toleration:
    key: node-role.kubernetes.io/qcss
    effect: NoSchedule
  label:
    key: node-role.kubernetes.io/worker
    value: infra

mbu:
  toleration:
    key: node-role.kubernetes.io/mbu
    effect: NoSchedule
  label:
    key: node-role.kubernetes.io/worker
    value: infra

worker:
  label:
    key: node-role.kubernetes.io/worker
    value: infra

processor:
  toleration:
    key: node-role.kubernetes.io/processor
    effect: NoSchedule
  label:
    key: node-role.kubernetes.io/processor
    value:
      aio: aio
      asp: asp
      l1: l1
      l2: l2
      zip: zip

kongplugin:
  clientId: "s1pdgs_client"
  clientSecret: ""
  discovery: "https://c1.ops.s1pdgs.eu/auth/realms/s1pdgs/.well-known/openid-configuration"
  sessionSecret: ""
  introspection_endpoint: "https://c1.ops.s1pdgs.eu/auth/realms/s1pdgs/protocol/openid-connect/token/introspect"
  groupsAuthorizedPaths:
    group:
    - name: "operations"
      path: "/odata"
    - name: "centreexpert"
      path: "/odata"
    - name: "op_manager"
      path: "/odata"
    - name: "sysadmin"
      path: "/odata"
    - name: "customer"
      path: "/odata"
    - name: "b2b"
      path: "/odata"

metadataCatalog:
  restApiNbRetry: 3
  restApiTempoRetryMs: 1000

auxip:
  serviceRootUri: "https://aux1.s1pdgs.eu/odata/v1"
  sslValidation: "false"
  authType: "oauth2"
  oauthAuthUrl: "https://aux1.s1pdgs.eu/auth/realms/s1pdgs/protocol/openid-connect/token"
  creationDateAttributeName: "PublicationDate"
  productNameAttrName: "Name"
  idAttrName: "Id"
  contentLengthAttrName: "ContentLength"
  start: "2021-02-22T08:30:00.000000"
  timeWindowSec: 240 #3600         # The time window to check at each request
  timeWindowOverlapSec: 240  # the current time window will have some overlap in seconds with the predecessing time window
                             # this is just to have the possibility to add some savety margin, making sure nothing is overseen between time windows
  offsetFromNowSec: 240      # time window will not reach now but now minus offset-from-now-sec
                             # this is for savety too, giving the queried system some grace period to provide new/current data
  maxPageSize: 500            # aux metadata will be splitted into pages with this size

xbip:
  bufferInputs: false
  ignoreFilesBeforeDate:
    cgs01:  "2021-02-23T10:00:00.000Z"
    cgs02:  "2021-02-23T10:00:00.000Z"
    cgs03:  "2021-02-23T10:00:00.000Z"
    cgs04:  "2021-02-23T10:00:00.000Z"
    cgs05:  "2021-02-23T10:00:00.000Z"
    cgs10:  "2021-02-23T10:00:00.000Z"
  stationRetentionTime:
    cgs01: 7
    cgs02: 7
    cgs03: 7
    cgs04: 7
    cgs05: 7
    cgs10: 7

edip:
  bufferInputs: false
  pedc:
    ignoreFilesBeforeDate: "2021-02-23T10:00:00.000Z"
    stationRetentionTime: 7
    host: 10.21.10.1
    path: /
    port: 21
    enablePasv: true
    explicitFtps: true
    disableCertificateCheck: false
    enableHostnameVerification: false
    enableDataChannelEncryption: false
    sslProtocol: TLSv1.2
    connectTimeoutSec: 60
    directory: "ftps://${edip.host}:${edip.port}${edip.path}NOMINAL/"
    matchRegex: '^([A-Za-z_]{4}/)?([0-9A-Za-z_]{2})([0-9A-Za-z_]{1})/([0-9A-Za-z_]+)/(ch[0|_]?[1-2]/)?(DCS_[0-9]{2}_([a-zA-Z0-9_]*)_ch([12])_(DSDB|DSIB).*\.(raw|aisp|xml|RAW|AISP|XML))$'
    topic: "t-pdgs-ingestion-jobs-edip-pedc-retransfer"
    family: "SESSION_RETRANSFER"
    keystore_data: ""
    keystore_pass: "changeit"
    truststore_data: /u3+7QAAAAIAAAABAAAAAgAIbXlvY2VhbjEAAAF3RQrFWwAFWC41MDkAAAPDMIIDvzCCAqegAwIBAgIUUbIDATMWy1AeVKX9P8A/0kaI5mEwDQYJKoZIhvcNAQELBQAwbzELMAkGA1UEBhMCREUxFTATBgNVBAgMDExvd2VyIFNheG9ueTESMBAGA1UEBwwJTHVlbmVidXJnMSEwHwYDVQQKDBhXZXJ1bSBTb2Z0d2FyZSAmIFN5c3RlbXMxEjAQBgNVBAMMCXMxcGRncy5ldTAeFw0yMDEyMDQxODQwMzhaFw0yMTEyMDQxODQwMzhaMG8xCzAJBgNVBAYTAkRFMRUwEwYDVQQIDAxMb3dlciBTYXhvbnkxEjAQBgNVBAcMCUx1ZW5lYnVyZzEhMB8GA1UECgwYV2VydW0gU29mdHdhcmUgJiBTeXN0ZW1zMRIwEAYDVQQDDAlzMXBkZ3MuZXUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZGsBDpcjrwGCY74UsujgSZkcQsRjv9TSCHimOV/dlvbDl58iIhZUg93uwub+Ae0F77pfPClN5YDjbepkT6qWWJd06AAUDlbylGELrnqNANpIiVqK2YVrOUR2qBnVDronOrrajeTD5bBAtPpjZssc5v3swhdqSLSBKTz/5LykOSvD4IpxKkdCJBu/L+y01kUGDe3eXYbbf4T1tjo11t4wJunUkv0RV2nvnPkrdu/YtTN9X7kw2LRNaHR0rHudo68F8m3PylC9HtDetK/bZ2gO23Vy5ZLriKpDi4cycqdAIUy0mBwjd3O4nQ353bh7T5l2zuPTcvysbtp9u5SbTLLLPAgMBAAGjUzBRMB0GA1UdDgQWBBRn55CvXWTHfl4RIavXecPpcM3AsDAfBgNVHSMEGDAWgBRn55CvXWTHfl4RIavXecPpcM3AsDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQDYXwNm4CnLsBXRj995oVaRuCG87F4srET7CzCrZUEy9QJYTxreB7oQz8dsFeW9SRbb5PaWhlnDwXjTIq03GUN3TIDLRcW4uEzRL/9rWv0Nl5hzdVo6GTFJ1drUTtzjtmv5laTs4gxF36R0xxl+TeYSgo41T78Fv6NIYvcABw5zdZoydbZyt2WkbWiJx8fkX5jbn+mXK3ECprhRYb6tMPUxeMRB0ZZEDrG7A+7qyLF9fpvx6m2qF80CaXKekxf4im2R7UjzqS0+b5c02JJnBpNrUvrjAabNh0Fd3omKjEGRoB5loK6c8t3rS5sr6PCr27wPLcSNT45u0P3FnsEYGnOZ5wEFmzWTWqty+5TotBFojPkkuQQ=
    truststore_pass: changeit
  bedc:
    ignoreFilesBeforeDate: "2021-02-23T10:00:00.000Z"
    stationRetentionTime: 7
    host: 10.22.10.1
    path: /
    port: 21
    enablePasv: true
    explicitFtps: true
    disableCertificateCheck: false
    enableHostnameVerification: false
    enableDataChannelEncryption: false
    sslProtocol: TLSv1.2
    connectTimeoutSec: 60
    directory: "ftps://${edip.host}:${edip.port}${edip.path}NOMINAL/"
    matchRegex: '^([A-Za-z_]{4}/)?([0-9A-Za-z_]{2})([0-9A-Za-z_]{1})/([0-9A-Za-z_]+)/(ch[0|_]?[1-2]/)?(DCS_[0-9]{2}_([a-zA-Z0-9_]*)_ch([12])_(DSDB|DSIB).*\.(raw|aisp|xml|RAW|AISP|XML))$'
    topic: "t-pdgs-ingestion-jobs-edip-bedc-retransfer"
    family: "SESSION_RETRANSFER"
    keystore_data: ""
    keystore_pass: "changeit"
    truststore_data: /u3+7QAAAAIAAAABAAAAAgAIbXlvY2VhbjEAAAF3RQrFWwAFWC41MDkAAAPDMIIDvzCCAqegAwIBAgIUUbIDATMWy1AeVKX9P8A/0kaI5mEwDQYJKoZIhvcNAQELBQAwbzELMAkGA1UEBhMCREUxFTATBgNVBAgMDExvd2VyIFNheG9ueTESMBAGA1UEBwwJTHVlbmVidXJnMSEwHwYDVQQKDBhXZXJ1bSBTb2Z0d2FyZSAmIFN5c3RlbXMxEjAQBgNVBAMMCXMxcGRncy5ldTAeFw0yMDEyMDQxODQwMzhaFw0yMTEyMDQxODQwMzhaMG8xCzAJBgNVBAYTAkRFMRUwEwYDVQQIDAxMb3dlciBTYXhvbnkxEjAQBgNVBAcMCUx1ZW5lYnVyZzEhMB8GA1UECgwYV2VydW0gU29mdHdhcmUgJiBTeXN0ZW1zMRIwEAYDVQQDDAlzMXBkZ3MuZXUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZGsBDpcjrwGCY74UsujgSZkcQsRjv9TSCHimOV/dlvbDl58iIhZUg93uwub+Ae0F77pfPClN5YDjbepkT6qWWJd06AAUDlbylGELrnqNANpIiVqK2YVrOUR2qBnVDronOrrajeTD5bBAtPpjZssc5v3swhdqSLSBKTz/5LykOSvD4IpxKkdCJBu/L+y01kUGDe3eXYbbf4T1tjo11t4wJunUkv0RV2nvnPkrdu/YtTN9X7kw2LRNaHR0rHudo68F8m3PylC9HtDetK/bZ2gO23Vy5ZLriKpDi4cycqdAIUy0mBwjd3O4nQ353bh7T5l2zuPTcvysbtp9u5SbTLLLPAgMBAAGjUzBRMB0GA1UdDgQWBBRn55CvXWTHfl4RIavXecPpcM3AsDAfBgNVHSMEGDAWgBRn55CvXWTHfl4RIavXecPpcM3AsDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQDYXwNm4CnLsBXRj995oVaRuCG87F4srET7CzCrZUEy9QJYTxreB7oQz8dsFeW9SRbb5PaWhlnDwXjTIq03GUN3TIDLRcW4uEzRL/9rWv0Nl5hzdVo6GTFJ1drUTtzjtmv5laTs4gxF36R0xxl+TeYSgo41T78Fv6NIYvcABw5zdZoydbZyt2WkbWiJx8fkX5jbn+mXK3ECprhRYb6tMPUxeMRB0ZZEDrG7A+7qyLF9fpvx6m2qF80CaXKekxf4im2R7UjzqS0+b5c02JJnBpNrUvrjAabNh0Fd3omKjEGRoB5loK6c8t3rS5sr6PCr27wPLcSNT45u0P3FnsEYGnOZ5wEFmzWTWqty+5TotBFojPkkuQQ=
    truststore_pass: changeit

dataLifecycle:
  retentionTimeUpdate:
    offsetInHoursL1: 6

disseminator:
  target:
    fos_hk_s1a: "fos-hk-s1a" # mock or fos-hk-s1a
    fos_hk_s1b: "fos-hk-s1b" # mock or fos-hk-s1a
    pod_gp: "pod-gp"         # mock or pod-gp
    pod_l0a: "pod-l0a"       # mock or pod-l0a
    mp: "mp"                 # mock or mp
    unav: "unav"             # mock or unav
    errmat: "errmat"         # mock or errmat
    myocean: "myocean"
    mbu: "mbu"
    qcss_app: "qcss-app"
    qcss_web: "qcss-web"
  outboxes:
    mock:
      protocol: sftp
      hostname: s1pro-mock-dissemination-svc.processing.svc.cluster.local
      port: 22
      username: foo
      password: pass
      path: /outboxes
    qcss:
      app:
        protocol: ftp
        hostname: qcss-online-server-svc.processing.svc.cluster.local
        port: 21
        username: s1pdgs
        password: changeit
        path: /data/in
        ftp_pasv: true
      web:
        protocol: ftp
        hostname: qcss-web-server-svc.processing.svc.cluster.local
        port: 21
        username: s1pdgs
        password: changeit
        path: /data/in
        ftp-pasv: true
    mp:
      protocol: sftp
      hostname: s1mis-ingestor-mp.monitoring.svc.cluster.local
      port: 22
      username: foo
      password: pass
      path: /in
      ftp-pasv: true
      truststore_pass: changeit
    unav:
      protocol: sftp
      hostname: s1mis-ingestor-unav.monitoring.svc.cluster.local
      port: 22
      username: foo
      password: pass
      path: /in
      ftp-pasv: true
      truststore_data:
    fos:
      hk_s1a:
        protocol: sftp
        hostname: senxser.esoc.ops.esa.int
        port: 22
        username: s1apdgs
        key-data: ""
        path: /home/s1apdgs/fromPDGS
        path-evaluator: ISIP
        ftp-pasv: true
        truststore_data:
      hk_s1b:
        protocol: sftp
        hostname: senxser.esoc.ops.esa.int
        port: 22
        username: s1bpdgs
        key-data: ""
        path: /home/s1bpdgs/fromPDGS
        path-evaluator: ISIP
    pod:
      gp:
        protocol: ftps
        hostname: cpodopsftp.gmv.com
        port: 21
        username: s1pdgs
        password: 
        path: /s1pdgs/gps_l0_products
        ftp-pasv: true
      l0a:
        protocol: ftps
        hostname: cpodopsftp.gmv.com
        port: 21
        username: s1pdgs
        password: 
        path: /s1pdgs/sar_l0_annotations_products
        ftp-pasv: true
    errmat:
      protocol: ftps
      hostname: aux1.s1pdgs.eu
      port: 2121
      username: s1pdgs
      password: "92ASBDdHNH2bQjJL"
      path: /
      ftp-pasv: true
      truststore_data: "/u3+7QAAAAIAAAABAAAAAgAFczFhdXgAAAF3sMFyZwAFWC41MDkAAAVXMIIFUzCCBDugAwIBAgISBImGObECcT13EHow+cpAeo7GMA0GCSqGSIb3DQEBCwUAMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQDExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDEwMjExMTMyNTFaFw0yMTAxMTkxMTMyNTFaMBkxFzAVBgNVBAMTDmF1eDEuczFwZGdzLmV1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn2GMM9mi1cHl0KfQW8l5uad3u/rQkx8SyoEp39aVd6cmK1i0Fy6XmWOfW2SdTaJGpcsyurKdhQhshWX+Gd1MLkI0ykSFRlFDf4c5B1vxEtsDg6HVfPdre1IhfIfSVFunJZiz/D2CPuJLV0ZrmsNZCUM9Mg9txIXjw5lBZ0gcOzXwO17w3uNv8klVHNcjxtmcZ2jqJ1MIS53JkqDyIgbBaSyJUGoSG1Ko2KSZcHDdFMVEm9lR6ywsi6zrVW/qS4GORtaLah4hLcPce00u5quOtGcrwAjlcJpXY1jaRSJ+RsY2XAdqNOXVxgpMVEvdfyod776kyhG1C+dhvrT3fEaOvwIDAQABo4ICYjCCAl4wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSMpD4qc5mJ/a/8TZUAVnOuMjbA0TAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEFBQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcvMBkGA1UdEQQSMBCCDmF1eDEuczFwZGdzLmV1MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHUARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAF1SyXU5AAABAMARjBEAiAkIqeJJ7YsoCGrBVkDIc2hWu6pGSatlV0gL/tvWYASZgIgUrCk7UJDohJFQR82aUENblZ5ien5aAsWO/gTjWf2OZ4AdgB9PvL4j/+IVWgkwsDKnlKJeSvFDngJfy5ql2iZfiLw1wAAAXVLJdUHAAAEAwBHMEUCIQDaM8IsdOWttzQoaVsccbliKoawaBLHJbLbIOLfc37wWwIgFg7209LMYK/yedwvNlZQ/peDoPYZKT/pDUVQ1yV3Gn0wDQYJKoZIhvcNAQELBQADggEBAF0LWwerlC65m1aSp/FSJreenCLRj00l64Z3sp+n4WR5wNpSzsGdlAMUKsVler1vVsNJUW0KUYEEWxYDDGhq8Vt/0hHNnKR5EM/Uc/Ksff2uLNswgroDwWdh3lFqPv2ciX0xFX055Lct6I5zhLf93/pa6cylpckQW1DypzVmxdreUx3cWWbu+67QyFEV2jc6mUVEKQof6zm6mkf8x8CyUQFVPCEr/GfMwl4hf9deQHIk9M7q1VlMNu/U1d/zRvhe33Udxavylj0cFmy6y8JJYlbXolPEev9PEybaKNH3w+1B+RI2SP6S12h/I/TNEUzIC86psbvPauOc+gF5j8UJ53AIhaOQBGKzLrXboEf977KfwWKS7w=="
      truststore-file: "/app/ssl/truststore.jks"
      truststore-pass: "changeit"
    myocean:
      protocol: ftps
      hostname: ops-c1-ftp-0001.cluster.local
      port: 21
      username: "s1pdgs"
      password: "CC8IiE0qwUSG"
      path: /public
      path-evaluator: myocean
      ftp-pasv: true
      truststore_data: "/u3+7QAAAAIAAAABAAAAAgAIbXlvY2VhbjEAAAF3dvvaaQAFWC41MDkAAAQJMIIEBTCCAu2gAwIBAgIJAJkj8VpmggbLMA0GCSqGSIb3DQEBCwUAMIGrMQswCQYDVQQGEwJGUjESMBAGA1UECAwJT2NjaXRhbmllMREwDwYDVQQHDAhUb3Vsb3VzZTEhMB8GA1UECgwYQWlyYnVzIERlZmVuY2UgYW5kIFNwYWNlMQ8wDQYDVQQLDAZTMVBER1MxFjAUBgNVBAMMDTkwLjg0LjE4MC4yMTExKTAnBgkqhkiG9w0BCQEWGnMxcGRnc19oZWxwZGVza0BhaXJidXMuY29tMB4XDTIxMDIwNDE2MzE0OFoXDTIzMDEyNTE2MzE0OFowgasxCzAJBgNVBAYTAkZSMRIwEAYDVQQIDAlPY2NpdGFuaWUxETAPBgNVBAcMCFRvdWxvdXNlMSEwHwYDVQQKDBhBaXJidXMgRGVmZW5jZSBhbmQgU3BhY2UxDzANBgNVBAsMBlMxUERHUzEWMBQGA1UEAwwNOTAuODQuMTgwLjIxMTEpMCcGCSqGSIb3DQEJARYaczFwZGdzX2hlbHBkZXNrQGFpcmJ1cy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDitDxITC3FVrq6O9HRHU8BvzNu9eP9RIdKES0PLUQaSwTU+mthTYz4p4ethbCPaUZ1RGnwbsye2PHlaIDnYZvv8f1ePEBQXzlvlaHP4IfCT3FpUkHi8HGtB6pkRlJfhD/mIMZejnGUHiHZ0IcToc6QCsrzKCnugIldE0/i9O+s0lJyu+a41t9+z9cdcISCw644L+rvrbKQqF3kWJD8nuzgX1MGAtFnCRHMGT4X8ilAor3yplsUevJXmmuQOEvp5W1G3DblsMk1xAasUe8PUzOgfWmQmY3n1vnaouq/QmieQZD0+XybVYkjDL0WQ5x16Yu+NxKT9EYqhOAYVie6VZrpAgMBAAGjKjAoMCYGA1UdEQQfMB2HBFpUtNOHBKwQNcKCD29wcy1jMS1mdHAtMDAwMTANBgkqhkiG9w0BAQsFAAOCAQEAI9im9wp0xkMSFu5Sa+ydOapysnNEnxDcHp7B5kjITV3nEixcLg6UU8s90DIMuY7Xx2GLw3HqGTTPw0ohUm/9dnfdhyGCAC+LECp5Z16QvtyuTLt6HH7/SG/yZW6LGaFTSpS2D/fwa0PIVWg3YgwFytt0sz8V5uLhGvj3vn7XXs1DLDc01mpM7uPFpktLeGAbjKKP3cLjGQP09FGA6PJGfazOykrYJ/odnvRh8iZaM6hPUcyvWy9JCN6UvsNmv3NZbaeUIMUmhqS5SsWRg5LIlP/nRehv6OsXsZqZxC52yPRBnjwY7qk6BKHBaG+2y0/NCKJhZzro8qjXn7tDD36DDJdE5J5uws8E1klgrOywqXZ2HryA"
      truststore-file: "/app/ssl/truststore.jks"
      truststore-pass: "changeit"
    mbu:
      protocol: ftp
      hostname: "s1pro-mock-dissemination-svc"
      port: 21
      username: s1pdgs
      password: "PDGS5!"
      path: public/METEO
      path_evaluator: mbu
      ftp_pasv: false
      keystore_data: ""
      keystore-file: "/path/to/keystore.jks"
      keystore-pass: "changeit"
      truststore_data: ""
      truststore-file: "/path/to/truststore.jks"
      truststore-pass: "changeit"

directorycleaner:
  myocean:
    schedule: "0 * * * *"
    protocol: ftp
    path: public
    port: 21
    user: s1pdgs
    pass: "PDG5!"
    host: s1pro-mock-dissemination-svc
    ftp_pasv: true
    retention_time_in_days: 7
    keystore_data: ""
    keystore_pass: "changeit"
    truststore_data: ""
    truststore_pass: "changeit"

preparator:
  aio:
    minimalWaitingTimeSec: 36000 
    timeoutSec:
      cgs1: 86400 # 7200
      cgs2: 86400 # 7200
      cgs3: 86400 # 7200
      cgs4: 86400 # 7200
      cgs5: 86400 # 7200
      edrs: 86400 # 7200
    descramble:
      cgs1: "yes"
      cgs2: "yes"
      cgs3: "yes"
      cgs4: "no"
      cgs5: "yes"
      edrs: "yes"
    rsEncode:
      cgs1: "yes"
      cgs2: "yes"
      cgs3: "yes"
      cgs4: "yes"
      cgs5: "yes"
      edrs: "yes"
  asp:
    late-topic-active: true   
    fast:
      minimal: 3 # 3
      nominal: 36 # 20
      late-after-milliseconds: 86400000 
    nrt:
      minimal: 3 # 1
      nominal: 36 # 2
      late-after-milliseconds: 10800000 
    pt:
      late-after-milliseconds: 10800000
  l1:
    late-topic-active: true   
    fast:
      late-after-milliseconds: 86400000 
    nrt:
      late-after-milliseconds: 10800000 
    pt:
      late-after-milliseconds: 10800000
  l2:
    late-topic-active: true   
    fast:
      late-after-milliseconds: 86400000 
    nrt:
      late-after-milliseconds: 10800000 
    pt:
      late-after-milliseconds: 10800000
      
appCatalog:
  mqi:
    cleaningOld: "172800000" # 2 day (1 day = 86400000)
  jobs:
    cleaningJobsTerminatedFixedRateMs: "604800000" # 7 days
    cleaningJobsInvalidFixedRateMs: "604800000"    # 7 days
    edrsSessions:
      maxAgeJobMs:
        waiting: "604800000"      # 7 days
        dispatching: "604800000"
        generating: "604800000"
        terminated: "604800000"
    levelSegments:
      maxAgeJobMs:
        waiting: "604800000"
        dispatching: "604800000"
        generating: "604800000"
        terminated: "604800000"
    levelProducts:
      maxAgeJobMs:
        waiting: "604800000" 
        dispatching: "604800000"
        generating: "604800000"
        terminated: "604800000" 

prometheusAdapter:
  prometheusUrl: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
  securePort: 6443
  metricsRelistInterval: 1m
  targets:
    xbip_worker:
      minReplicas: 2
      maxReplicas: 4
      scaleDown:
        stabilizationWindowSeconds: 300
        selectPolicy: Max
      scaleUp:
        stabilizationWindowSeconds: 10
        selectPolicy: Max