kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.processing.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount.mock_webdav_cgs01 }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.processing.namespace }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.worker.label.key }}
                operator: In
                values:
                - {{ .Values.worker.label.value }}
      containers:
      - name: {{ .Release.Name }}-webdav
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - name: webdav
          protocol: TCP
          containerPort: 80
        - name: webdavtls
          protocol: TCP
          containerPort: 443        
        volumeMounts: 
        - name: webdavdatadir
          mountPath: /var/lib/dav     
        env:
        - name: AUTH_TYPE
          value: "Basic"
        - name: SSL_CERT
          value: "selfsigned"
        - name: USERNAME
          value: "xbip_werum"
        - name: PASSWORD
          value: "bWmMeluCz-1"       
        livenessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        securityContext:
          privileged: false
      initContainers:
      - name: init-dav
        image: registry.tools.s1pdgs.eu/anonymous/busybox:1.28
        command: ['sh', '-c', "mkdir -p /var/lib/dav/data/AUX /var/lib/dav/data/NOMINAL/WILE/S1B /var/lib/dav/data/RETRANSFER/WILE/S1B && touch /var/lib/dav/DavLock && chown -R www-data:www-data /var/lib/dav" ]
        volumeMounts: 
        - name: webdavdatadir
          mountPath: /var/lib/dav        
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      subdomain: {{ .Release.Name }}-svc
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: {{ .Release.Name }}-svc
  revisionHistoryLimit: 10
  volumeClaimTemplates:  
  - metadata:
      name: webdavdatadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ default "500Gi" (default dict (default dict .Values.mockWebDav).cgs01).storageSize }}