name: 'Build RS-Core components'
description: 'Build release artifacts for the RS-core chains'
inputs:
  WERUM_ARTIFACTORY_USER:
    description: 'Username for Artifactory'
    required: true
  WERUM_ARTIFACTORY_PASSWORD:
    description: 'Password for Artifactory'
    required: true

runs:
  using: "composite"
  steps:
  - name: Extract branch or tag name
    shell: bash
    run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | cut -d / -f3-)"
    id: extract_branch
    
  - name: Generate file name
    shell: bash
    run: |
      corecomp=${{ matrix.component }}
      corefilename="RS_CORE_${corecomp^^}_${{ steps.extract_branch.outputs.branch }}"
      echo "##[set-output name=filename;]$(echo ${corefilename})"
    id: gen_filename
    
  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
    
  - name: Build structure
    shell: bash
    run: |
      mkdir -p ${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Executables/additional_resources
      sed -i 's/<VERSION>/${{ steps.extract_branch.outputs.branch }}/' ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/content/stream-application-list.properties
      cat ${{ env.RS_CORE_FOLDER }}/obs-stream-parameters.properties >> ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/content/stream-parameters.properties
      cat ${{ env.RS_CORE_FOLDER }}/common-parameters.properties >> ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/content/stream-parameters.properties
      chain_name_upper=$(echo ${{ matrix.component^^}})      
      sed -i 's/<CHAIN_NAME>/${{ chain_name_upper }}/' ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/content/stream-parameters.properties
      sed -i 's/<CHAIN_VERSION>/${{ steps.extract_branch.outputs.branch }}/' ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/content/stream-parameters.properties
      cp -r ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/content/* ${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Executables
      if [[ -e ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/additional_resources ]] 
        then cp -r ${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/additional_resources/* ${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Executables/additional_resources
      fi

  - name: Create PDF
    uses: docker://ghcr.io/coprs/reference-system-software:dependencies_pandoc_latex
    with:
      args: -s --resource-path="/github/workspace/${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/doc" --listings -H /root/.pandoc/listings-setup.tex --table-of-contents --pdf-engine=xelatex --output="${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Release_Note.pdf" --from=markdown "./${{ env.RS_CORE_FOLDER }}/${{ matrix.component }}/doc/SRN.md"
  
  - name: Install zip
    uses: montudor/action-zip@v1
  
  - name: Zip
    shell: bash
    run: |
      cd ${{ steps.gen_filename.outputs.filename }}
      zip -qq -r ../${{ steps.gen_filename.outputs.filename }}.zip *
      
  - name: Push to Artifactory
    shell: bash
    run: curl -u "${{ inputs.WERUM_ARTIFACTORY_USER }}:${{ inputs.WERUM_ARTIFACTORY_PASSWORD }}" -T ${{ steps.gen_filename.outputs.filename }}.zip "https://${{ env.ARTIFACTORY_BASE }}/artifactory/${{ env.ARTIFACTORY_PROJECT_COMMON }}/${{ env.ARTIFACTORY_CORE_PROJECT }}/"   
