# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: registry.tools.s1pdgs.eu/anonymous/docker:latest

variables:
  MODULE_DATA_REQUEST_WORKER: s1pro-core-data-request-worker

data-request-worker-build:
  stage: module
  script:
    - cd data-request-worker
    - dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_DATA_REQUEST_WORKER:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_DATA_REQUEST_WORKER:$CI_COMMIT_REF_SLUG"
