kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.processing.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount.ingestion_edip_pedc_worker }}
  podManagementPolicy: Parallel
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.processing.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.gateway.label.key }}
                operator: In
                values:
                - {{ .Values.gateway.label.value.edrs.pedc }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.ingestion_edip_pedc_worker.ram.request }}
            cpu: {{ .Values.ingestion_edip_pedc_worker.cpu.request }}
          limits:
            memory: {{ .Values.ingestion_edip_pedc_worker.ram.limit }}
            cpu: {{ .Values.ingestion_edip_pedc_worker.cpu.limit }}
        volumeMounts:
        - name: service-logging-config-volume
          mountPath: /app/log
        - name: service-config-volume
          mountPath: /app/config
        - name: service-ssl-config-volume
          mountPath: /app/ssl
        - name: s3-upload-cache
          mountPath: {{ .Values.ingestion_edip_pedc_worker.uploadCache.location }}
        ports:
        - name: web
          protocol: TCP
          containerPort: {{ .Values.service.port }}
        env:
        - name: JAVA_XMS
          value: {{ .Values.ingestion_edip_pedc_worker.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.ingestion_edip_pedc_worker.javaOpts.xmx }}
        - name: storage_user_id
          valueFrom:
            secretKeyRef:
              name: obs
              key: USER_ID
        - name: storage_user_secret
          valueFrom:
            secretKeyRef:
              name: obs
              key: USER_SECRET
        - name: edip.user
          valueFrom:
            secretKeyRef:
              name: edip-pedc
              key: USER
        - name: edip.pass
          valueFrom:
            secretKeyRef:
              name: edip-pedc
              key: PASS
        envFrom:
        - configMapRef:
            name: s1pdgs-config
        - configMapRef:
            name: s1pdgs-logging-config
        - configMapRef:
            name: s1pdgs-env
        - configMapRef:
            name: s1pdgs-edip-pedc
        securityContext:
          privileged: false
        livenessProbe:
          httpGet:
            path: /app/status
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
      - name: {{ .Release.Name }}-mqi
        image: {{ .Values.mqiImage.registry }}/{{ .Values.mqiImage.repository }}/{{ .Values.mqiImage.name }}:{{ .Values.mqiImage.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.ingestion_edip_pedc_worker_mqi.ram.request }}
            cpu: {{ .Values.ingestion_edip_pedc_worker_mqi.cpu.request }}
          limits:
            memory: {{ .Values.ingestion_edip_pedc_worker_mqi.ram.limit }}
            cpu: {{ .Values.ingestion_edip_pedc_worker_mqi.cpu.limit }}
        volumeMounts:
        - name: service-logging-config-volume
          mountPath: /app/log
        - name: mqi-config-volume
          mountPath: /app/config
        ports:
        - name: data
          protocol: TCP
          containerPort: {{ .Values.mqiService.port }}
        env:
        - name: JAVA_XMS
          value: {{ .Values.ingestion_edip_pedc_worker_mqi.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.ingestion_edip_pedc_worker_mqi.javaOpts.xmx }}
        envFrom:
        - configMapRef:
            name: s1pdgs-config
        - configMapRef:
            name: s1pdgs-logging-config
        - configMapRef:
            name: s1pdgs-env
        livenessProbe:
          httpGet:
            path: /app/status
            port: {{ .Values.mqiService.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
      tolerations:
      - key: {{ .Values.gateway.toleration.key }}
        operator: "Exists"
        effect: {{ .Values.gateway.toleration.effect }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      subdomain: {{ .Release.Name }}-svc
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: service-logging-config-volume
          configMap:
            name: s1pdgs-logging-config
        - name: service-config-volume
          configMap:
            name: {{ .Release.Name }}-service-config
        - name: service-ssl-config-volume
          configMap:
            name: {{ .Release.Name }}-service-ssl-config
        - name: mqi-config-volume
          configMap:
            name: {{ .Release.Name }}-mqi-config
        - name: s3-upload-cache
          emptyDir:
            medium: {{ .Values.ingestion_edip_pedc_worker.uploadCache.medium }}
            sizeLimit: {{ .Values.ingestion_edip_pedc_worker.uploadCache.size }}
  serviceName: {{ .Release.Name }}-svc
  revisionHistoryLimit: 10
