 name: 'Build Libs'
 description: 'Builds libraries'
 inputs:
   secrets-gitguardian-api-key:
     required: true
   secrets-sonarqube-host:
     required: true
   secrets-sonarqube-token:
     required: true
   secrets-artifactory-user:
     required: true
   secrets-artifactory-password:
     required: true
   artifactory-base:
     required: true
   artifactory-project:
     required: true
     
 runs:
   using: "composite"
   steps:
     - name: Set environment variables
       run: |
         # Short name for current branch. For PRs, use target branch (base ref)
         GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF/refs/heads/}}
         echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
       shell: bash

     - name: GitGuardian scan
       uses: GitGuardian/gg-shield-action@master
       env:
         GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }} 
         GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
         GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
         GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
         GITGUARDIAN_API_KEY: ${{ inputs.secrets-gitguardian-api-key }}
          
     - name: Set up JDK 8
       uses: actions/setup-java@v2
       with:
         java-version: '8'
         distribution: 'adopt'
          
     - name: sonarqube scan 
       run: |
         pwd
         ls
         cd rs-libs
         mvn sonar:sonar -Dsonar.projectKey=${{github.repository}} -Dsonar.host.url=${{ inputs.secrets-sonarqube-host }} -Dsonar.login=${{ inputs.secrets-sonarqube-token }} -Dsonar.branch.name=${{ env.GIT_BRANCH }}
       shell: bash
       
     - name: Build jar 
       run: mvn clean install
       shell: bash
          
     - name: Setup Maven settings.xml
       uses: whelk-io/maven-settings-xml-action@v11
       with:
         servers: '[{"id": "artifactory","username": "${{ inputs.secrets-artifactory-user }}", "password": "${{ inputs.secrets-artifactory-password }}"}]'
        
     - name: Push to Artifactory
       run: mvn jar:jar deploy:deploy -Dfile=target/*.jar -DrepositoryId=artifactory -DpomFile=pom.xml -DaltDeploymentRepository=artifactory::default::https://${{ inputs.artifactory-base }}/artifactory/${{ inputs.artifactory-project }}
       shell: bash