name: 'Build Libs'
description: 'Build libs'
inputs:
  COMPONENT:
    required: true
  ARTIFACTORY_BASE:
    required: true
  ARTIFACTORY_PROJECT:
    required: true
  WERUM_ARTIFACTORY_USER:
    required: true
  WERUM_ARTIFACTORY_PASSWORD:
    required: true
  SONARQUBE_HOST:
    required: true
  SONARQUBE_TOKEN:
    required: true
    
runs:
  using: "composite"
  steps:
    
  - name: Set environment variables
    shell: bash
    run: |
      # Short name for current branch. For PRs, use target branch (base ref)
      GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF/refs/heads/}}
      echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      
  - name: Set up JDK 8
    uses: actions/setup-java@v2
    with:
      java-version: '8'
      distribution: 'adopt'
  
  - name: Setup Maven settings.xml
    uses: whelk-io/maven-settings-xml-action@v11
    with:
      repositories: '[{ "id": "artifactory", "url": "https://${{ inputs.ARTIFACTORY_BASE }}/artifactory/${{ inputs.ARTIFACTORY_PROJECT }}" }]'
      servers: '[{"id": "artifactory","username": "${{ inputs.WERUM_ARTIFACTORY_USER }}", "password": "${{ inputs.WERUM_ARTIFACTORY_PASSWORD }}"}]'
  
  - name: Build jar 
    shell: bash
    run: |
      cd rs-libs/${{ inputs.COMPONENT }}
      mvn clean install 
      
  - name: Sonarqube scan 
    shell: bash
    run: |
      cd rs-libs/${{ inputs.COMPONENT }}
      mvn sonar:sonar -Dsonar.projectKey=${{github.repository}} -Dsonar.host.url=${{ inputs.SONARQUBE_HOST }} -Dsonar.login=${{ inputs.SONARQUBE_TOKEN }} -Dsonar.branch.name=${{ env.GIT_BRANCH }}
      

  - name: Push to Artifactory
    shell: bash
    run: |
      cd rs-libs/${{ inputs.COMPONENT }}
      mvn jar:jar deploy:deploy -Dfile=target/*.jar -DrepositoryId=artifactory -DpomFile=pom.xml -DaltDeploymentRepository=artifactory::default::https://${{ inputs.ARTIFACTORY_BASE }}/artifactory/${{ inputs.ARTIFACTORY_PROJECT }}
      if [ "${{ inputs.COMPONENT }}" = "obs-sdk" ]; then mvn jar:test-jar deploy:deploy -Dfile=target/*-tests.jar -DrepositoryId=artifactory -DpomFile=pom.xml -DaltDeploymentRepository=artifactory::default::https://${{ inputs.ARTIFACTORY_BASE }}/artifactory/${{ inputs.ARTIFACTORY_PROJECT }}; fi
