apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: catalog-event
  labels:
    strimzi.io/cluster: kafka-cluster
    app.kubernetes.io/instance: metadata-extraction
    app.kubernetes.io/managed-by: additional_resources
spec:
  partitions: 2
  replicas: 4
  config:
    retention.bytes: 89478485
    retention.ms: "-1"
    segment.bytes: 22369621
    cleanup.policy: delete
    min.insync.replicas: 2
