# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  MODULE_WRAPPER: s1pro-core-wrapper

wrapper-l0-build-master:
  stage: module
  script:
    - cd wrapper
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0" -f wrapper/config/dockerfiles/Dockerfile_L0 Dockerfile
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0"
  only:
    - master

wrapper-l0-build:
  stage: module
  script:
    - cd wrapper
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0:$CI_COMMIT_REF_SLUG" - < config/dockerfiles/Dockerfile_L0 Dockerfile
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0:$CI_COMMIT_REF_SLUG"
  except:
    - master
    
wrapper-l0-segment-build:
  stage: module
  script:
    - cd wrapper
    - docker --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0-segment:$CI_COMMIT_REF_SLUG" build - < config/dockerfiles/Dockerfile_L0_segment
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1:$CI_COMMIT_REF_SLUG"
  except:
    - master

wrapper-l1-build:
  stage: module
  script:
    - cd wrapper
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1:$CI_COMMIT_REF_SLUG" - < config/dockerfiles/Dockerfile_L1 Dockerfile
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1:$CI_COMMIT_REF_SLUG"
  except:
    - master
    
    