# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  MODULE_WRAPPER: s1pro-core-wrapper

wrapper-l0-build-master:
  stage: module
  script:
    - cd wrapper
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0" -f config/dockerfiles/Dockerfile_L0 Dockerfile
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0"
  only:
    - master

wrapper-l0-build:
  stage: module
  script:
    - cd wrapper
    - docker build --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0:$CI_COMMIT_REF_SLUG" -f config/dockerfiles/Dockerfile_L0 Dockerfile
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0:$CI_COMMIT_REF_SLUG"
  except:
    - master
