before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

stages:
  - build
  - push_dev
  - push_master
  - push_tag

build:
  stage: build
  tags:
  - docker
  script:
  - cp config/dockerfiles/Dockerfile_L0 Dockerfile
  - docker build -t $CI_PROJECT_NAME/l0:$CI_COMMIT_REF_NAME .
  - cp config/dockerfiles/Dockerfile_L1 Dockerfile
  - docker build -t $CI_PROJECT_NAME/l1:$CI_COMMIT_REF_NAME .
  - cp config/dockerfiles/Dockerfile_L0_segment Dockerfile
  - docker build -t $CI_PROJECT_NAME/l0_segment:$CI_COMMIT_REF_NAME .

push_dev:
  stage: push_dev
  tags:
  - docker
  except:
    - tags
    - master
  script:
    - docker tag $CI_PROJECT_NAME/l0:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0:$CI_COMMIT_REF_NAME
    - docker tag $CI_PROJECT_NAME/l1:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l1:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l1:$CI_COMMIT_REF_NAME
    - docker tag $CI_PROJECT_NAME/l0_segment:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0_segment:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0_segment:$CI_COMMIT_REF_NAME

push_master:
  stage: push_master
  tags:
  - docker
  only:
    - master
  script:
    - docker tag $CI_PROJECT_NAME/l0:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0:latest
    - docker tag $CI_PROJECT_NAME/l1:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l1:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l1:latest
    - docker tag $CI_PROJECT_NAME/l0_segment:$CI_COMMIT_REF_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0_segment:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0_segment:latest

push_tag:
  stage: push_tag
  tags:
  - docker
  only:
    - tags
  script:
    - docker tag $CI_PROJECT_NAME/l0:$CI_COMMIT_TAG $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0:$CI_COMMIT_TAG
    - docker tag $CI_PROJECT_NAME/l1:$CI_COMMIT_TAG $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l1:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l1:$CI_COMMIT_TAG
    - docker tag $CI_PROJECT_NAME/l0_segment:$CI_COMMIT_TAG $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0_segment:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/l0_segment:$CI_COMMIT_TAG

