# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  MODULE_WRAPPER: s1pro-core-wrapper

# Build wrapper for master branch
wrapper-l0-build-master:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L0 | dockerbuild -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0"
  only:
    - master
    
wrapper-l0-segment-build-master:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L0_segment | dockerbuild -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0-segment" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0-segment"
  only:
    - master
    
wrapper-l1-build-master:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L1 | dockerbuild -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1"
  only:
    - master

wrapper-l2-build-master:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L2 | dockerbuild -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l2" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l2"
  only:
    - master
        
# Build wrapper for develop and other branches
wrapper-l0-build:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L0 | dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final --network host --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0:$CI_COMMIT_REF_SLUG" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0:$CI_COMMIT_REF_SLUG"
  except:
    - master
    
wrapper-l0-segment-build:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L0_segment | dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0-segment:$CI_COMMIT_REF_SLUG" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l0-segment:$CI_COMMIT_REF_SLUG"
  except:
    - master

wrapper-l1-build:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L1 | dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1:$CI_COMMIT_REF_SLUG" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l1:$CI_COMMIT_REF_SLUG"
  except:
    - master
wrapper-l2-build:
  stage: module
  script:
    - cd wrapper
    - cat config/dockerfiles/Dockerfile_L2 | dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l2:$CI_COMMIT_REF_SLUG" -
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_WRAPPER-l2:$CI_COMMIT_REF_SLUG"
  except:
    - master
    