kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.processing.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount.metadata_catalog_worker }}
  podManagementPolicy: Parallel
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.processing.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.worker.label.key }}
                operator: In
                values:
                - {{ .Values.worker.label.value }}
      containers:

      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.s1pro_metadata_catalog_worker.ram.request }}
            cpu: {{ .Values.s1pro_metadata_catalog_worker.cpu.request }}
          limits:
            memory: {{ .Values.s1pro_metadata_catalog_worker.ram.limit }}
            cpu: {{ .Values.s1pro_metadata_catalog_worker.cpu.limit }}

        volumeMounts:
        - name: service-logging-config-volume
          mountPath: /app/log
        - name: service-config-volume
          mountPath: /app/config
        - name: xslt-config-volume
          mountPath: /app/xslt
        ports:
        - name: web
          protocol: TCP
          containerPort: {{ .Values.service.port }}
        securityContext:
          privileged: false
        env:
        - name: JAVA_XMS
          value: {{ .Values.s1pro_metadata_catalog_worker.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.s1pro_metadata_catalog_worker.javaOpts.xmx }}
        - name: storage_user_id
          valueFrom:
            secretKeyRef:
              name: obs
              key: USER_ID
        - name: storage_user_secret
          valueFrom:
            secretKeyRef:
              name: obs
              key: USER_SECRET
        envFrom:
        - configMapRef:
            name: s1pdgs-config
        - configMapRef:
            name: s1pdgs-logging-config
        - configMapRef:
            name: s1pdgs-env
        livenessProbe:
          httpGet:
            path: /app/status
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          
      - name: {{ .Release.Name }}-mqi
        image: {{ .Values.mqiImage.registry }}/{{ .Values.mqiImage.repository }}/{{ .Values.mqiImage.name }}:{{ .Values.mqiImage.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.s1pro_metadata_catalog_worker_mqi.ram.request }}
            cpu: {{ .Values.s1pro_metadata_catalog_worker_mqi.cpu.request }}
          limits:
            memory: {{ .Values.s1pro_metadata_catalog_worker_mqi.ram.limit }}
            cpu: {{ .Values.s1pro_metadata_catalog_worker_mqi.cpu.limit }}
        volumeMounts:
        - name: service-logging-config-volume
          mountPath: /app/log
        - name: mqi-config-volume
          mountPath: /app/config
        ports:
        - name: data
          protocol: TCP
          containerPort: {{ .Values.mqiService.port }}
        env:
        - name: JAVA_XMS
          value: {{ .Values.s1pro_metadata_catalog_worker_mqi.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.s1pro_metadata_catalog_worker_mqi.javaOpts.xmx }}
        envFrom:
        - configMapRef:
            name: s1pdgs-config
        - configMapRef:
            name: s1pdgs-logging-config
        - configMapRef:
            name: s1pdgs-env
        livenessProbe:
          httpGet:
            path: /app/status
            port: {{ .Values.mqiService.port }}
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      subdomain: {{ .Release.Name }}-svc
      volumes:
        - name: service-logging-config-volume
          configMap:
            name: s1pdgs-logging-config
        - name: service-config-volume
          configMap:
            name: {{ .Release.Name }}-service-config
        - name: xslt-config-volume
          configMap:
            name: {{ .Release.Name }}-xslt-config
        - name: mqi-config-volume
          configMap:
            name: {{ .Release.Name }}-mqi-config
  serviceName: {{ .Release.Name }}-svc
  revisionHistoryLimit: 10

