# Copyright 2023 Airbus
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
  namespace: {{ .Values.processing.namespace }}
  
data:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "config/app/**" }}
  {{- $name := base $path }}
  {{ $name }} : |-
{{ (tpl ($.Files.Get (printf "%s" $path)) $ ) | indent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logging-config
  namespace: {{ .Values.processing.namespace }}
  
data:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "config/log/**" }}
  {{- $name := base $path }}
  {{ $name }} : |-
{{ (tpl ($.Files.Get (printf "%s" $path)) $ ) | indent 4 }}
  {{- end }}
---
