variables:
  MODUL: "app-catalog-client"  
   
app-catalog-client-build-master:
  stage: build
  script:
    - cd $MODUL
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODUL" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODUL"
  only:
    - master

app-catalog-client-build:
  stage: build
  script:
    - cd $MODUL
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODUL:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODUL:$CI_COMMIT_REF_SLUG"
  except:
    - master