spring:
  main:
    banner-mode: "off"
  application:
    name: s1pdgs-compression-trigger
    
# Logging config
logging:
  config: ${log4j_config:log/log4j2.yml}

# Application status configuration
status:
  # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not, default is 3000
  delete-fixed-delay-ms: 1800000
  # The number of consecutive processing errors leading to the state FATALERROR, default is 100
  max-error-counter-processing: 3
  # The number of consecutive MQI errors leading to the state FATALERROR, default is 100
  max-error-counter-mqi: 30

# Generic application config
process:
  # Hostname
  hostname: ${HOSTNAME}

# Kafka config
kafka:
  # host:port to use for establishing the initial connection to the Kafka cluster
  bootstrap-servers: ${kafka_bootstrap-servers}
  # Hostname
  hostname: ${HOSTNAME}
  # Topic name for the errors
  error-topic: ${kafka_topic_errors}
  # Kafka Producer config
  producer:
    # When greater than zero, enables retrying of failed sends
    max-retries: 10

# Compression Trigger config
trigger:
  # Categories to observe for files to compress/uncompress
  product-categories:
    level-products:
      # (Fixed delay) Period in milliseconds between 2 polls of next message
      fixed-delay-ms: 500
      # Initial delay in milliseconds before starting consuming message 
      init-delay-poll-ms: 2000 
    level-segments:
      # (Fixed delay) Period in milliseconds between 2 polls of next message
      fixed-delay-ms: 500 
      # Initial delay in milliseconds before starting consuming message 
      init-delay-poll-ms: 2000
    spp-products:
      # (Fixed delay) Period in milliseconds between 2 polls of next message
      fixed-delay-ms: 500
      # Initial delay in milliseconds before starting consuming message 
      init-delay-poll-ms: 2000
    ingestion-event:
      # (Fixed delay) Period in milliseconds between 2 polls of next message
      fixed-delay-ms: 500
      # Initial delay in milliseconds before starting consuming message 
      init-delay-poll-ms: 2000
    data-request-event:
      # (Fixed delay) Period in milliseconds between 2 polls of next message
      fixed-delay-ms: 500
      # Initial delay in milliseconds before starting consuming message 
      init-delay-poll-ms: 2000

# MQI config
mqi:
  # The host and port for querying MQI server
  host-uri: http://localhost:8081
  # The maximal number of consecutive retries following a MQI request error, default is 3 
  max-retries: 45
  # Time between retries in milliseconds, default is 1000
  tempo-retry-ms: 2000
  # Message Filter to accept/deny messages
  message-filter:
  # ProductFamily to apply filter rule on
  - productFamily: L0_SEGMENT
    # Regular expression to allow messages
    allowRegex: S1._(GP|HK|RF).*_RAW.*\.SAFE
    # Regular expression to disallow messages
    disallowRegex: S1._RF_RAW__0.(HH|HV|VV|VH)_.*\.SAFE
  - productFamily: AUXILIARY_FILE
    # Regular expression to disallow messages
    disallowRegex: S1__OPER_MSK_EW_SLC_.*\.EOF
