# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: registry.tools.s1pdgs.eu/anonymous/docker:latest

variables:
  MODULE_OUTBOX_CLEANER: s1pro-core-outbox-cleaner

outbox-cleaner-build:
  stage: module
  script:
    - cd outbox-cleaner
    - dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_OUTBOX_CLEANER:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_OUTBOX_CLEANER:$CI_COMMIT_REF_SLUG"
