# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  MODULE_DISSEMINATION_WORKER: s1pro-core-dissemination-worker

dissemination-worker-build:
  stage: module
  script:
    - cd dissemination-worker
    - dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_DISSEMINATION_WORKER:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_DISSEMINATION_WORKER:$CI_COMMIT_REF_SLUG"
