#!/bin/sh

if [ -z "$LOCATION" ]
then
    echo "Please source environment"
    exit 1
fi

{
  source "$LOCATION/werum/scripts/lib/functions"

  clean_inbox_polling
  clean_webdav_mock
  clean_edip_mock

  echo "Cleaning environment..."
  WERUM_SKIP_KAFKA_CLEAN=true "${LOCATION}/wrapper.sh" "${ENV_DIR}/wrapper/configuration.sh" clean
  #WERUM_FAST_KAFKA_INIT=true init_cluster
  safe_es_clean all
  #deploy il
  echo "done."
} 2>&1 | tee "/tmp/clean_all_$(date +%Y-%m-%d_%H-%M-%S).log"
