#!/bin/sh

HELM_DIR=$LOCATION/helm

if [ -z $ENV_DIR ]; then
    echo "Please set environment variable \$ENV_DIR pointing to the environment specific configuration"
    exit 1
fi

if [ -z $LOCATION ]; then
    echo "Please source environment"
    exit 1
fi

if [ $# -lt 1 -o $# -gt 2 ]; then
    echo "Synopsis: INSTALL|UNINSTALL [CHART_DIR]"
    echo "Option CHART_DIR allows to (un-)deploy a single service"
    exit 1
fi

ACTION="$1"
CHART_DIR="$2"

CONF_DIR="$ENV_DIR/wrapper/configuration.sh" # Actually this is the config dir not the env...?

deploy() {
    local CHART_DIR=$1
    local LOCAL_INST=${2:-false}
    if [ -z $CHART_DIR ]; then
        echo "Deploying all services"
	else
	    echo "Deploying service $CHART_DIR"
	fi
    $LOCATION/modules/deploy.sh $CONF_DIR init "$CHART_DIR" ${LOCAL_INST}
    echo "done."
}

undeploy() {
    local CHART_DIR="$1"
    local LOCAL_INST=${2:-false}
    if [ -z $CHART_DIR ]; then
        echo "Undeploying all services"
	else
        echo "Undeploying service $CHART_DIR"
	fi
    $LOCATION/modules/deploy.sh $CONF_DIR clean "$CHART_DIR" ${LOCAL_INST}
    echo "done."
}

check() {
    local CHART_DIR="$1"
    if [ -z $CHART_DIR ]; then
        echo "Checking all services"
	else
        echo "Check service $CHART_DIR"
	fi
    $LOCATION/modules/deploy.sh $CONF_DIR check "$CHART_DIR"
    echo "done."
}

case "$ACTION" in
  "INSTALL"|i) deploy "$CHART_DIR" false;;
  "UNINSTALL"|u) undeploy "$CHART_DIR" false;;
  "INSTALL_LOCAL"|il) deploy "$CHART_DIR" true;;
  "UNINSTALL_LOCAL"|ul) undeploy "$CHART_DIR" true;;
  "CHECK"|c) check "$CHART_DIR";;
  *) echo "invalid action: $ACTION";;
esac
