#!/bin/sh

if [ -z $ENV_DIR ]
then
  echo "Please set environment variable \$ENV_DIR pointing to the environment specific configuration"
  exit 1
fi 

if [ -z $LOCATION ]
then
    echo "Please source environment"
    exit 1
fi

$LOCATION/wrapper.sh $ENV_DIR/wrapper/configuration.sh init

echo "Ingesting landmask file"
cd ~/s1pro-api/MSK__LAND_/example/
landmask INGEST S1__OPER_MSK__LAND__V20140403T210200_G20200914T080808.EOF

echo "Scaling down"
$ENV_DIR/s1pro-env-scale.sh

echo "done."
