#!/bin/sh
if [ -z $LOCATION ]
then
    echo "Please source environment"
    exit 1
fi

if [ -z $ENV_DIR ]
then
  echo "Please set environment variable \$ENV_DIR pointing to the environment specific configuration"
  exit 1
fi 

if [ $# -ne 1 ]
then
    echo "Please provide a target: ALL or PRODUCED"
    exit 1
fi

if [ $1 == "ALL" ]
then
  $LOCATION/module/s3.sh $ENV_DIR/configuration/template-s3.sh reset
else
  PROTECT_S3="^(.*auxiliary-files|.*-session-files)$" $LOCATION/module/s3.sh $ENV_DIR/configuration/template-s3.sh reset
fi 

echo "done."