#!/bin/bash

for podName in $(kubectl -n $S1PRO_NAMESPACE get pods | sed -e "1d" | cut -d ' ' -f1)
do 
  for containerName in $(kubectl -n $S1PRO_NAMESPACE get pods ${podName} -o jsonpath={.spec.containers[*].name})
  do
    >&2 echo "=================================================> ${podName} ${containerName}" 
    kubectl -n $S1PRO_NAMESPACE exec -it ${podName} -c ${containerName} -- cat report.json
  done
done
