#!/bin/sh

if [ -z $LOCATION ]
then
    echo "Please source environment"
    exit 1
fi

echo "Invoking validation ..."

kubectl -n $S1PRO_NAMESPACE exec -ti s1pro-validation-0 -- wget -O - "http://localhost:8080/api/v1/validate" --post-data ""
 
echo "done."
