#!/bin/bash
#
# This script allows to deploy or undeploy the charts for different
# addons of the reference system. So it is possible to deploy just the
# common microservices or a mission specific aspect.
#
# It is a fascade for the existing scripts of S1PRO and tries to reuse these
# scripts as best as possible, but providing lean and easy to use interface
# for deploying microservices in the contex to V1.
#

# Give some hints on how to use the script
usage() {
  echo "Usage $0: <CMD> <ADDON> <SERVICE>"
  echo -e "\t  CMD \t\t install|uninstall|restart"
  echo -e "\t  ADDON \t common|infra|s1|s3"
  #echo -e "\t  SERVICE \t Name of a specific service that shall be handled. Can be left empty for all."
  echo 
  echo "ex. ./rs_deploy install s1"
  echo "Will deploy all microservices contain in the RS Addon S1"
  
  exit 1
}

# We need at least a command and a addon. If this is not there, we can stop.
if [[ $# -lt 2 ]]
then
  echo "Wrong number of arguments"
  usage
fi

CMD=$1
export ADDON=$2

# Check that the addon is known
if [[ ! $ADDON =~ ^(s1|s3|infra|common)$ ]]
then
  echo "Unknown addon: $ADDON"
  usage
fi

rs_install() {
  echo "Installing addon $ADDON"
  deploy il $ADDON
}

rs_uninstall() {
  echo "Uninstalling addon $ADDON"
  deploy UNINSTALL $ADDON
}

rs_restart() {
  echo "Performing restart of addon $ADDON"
  rs_uninstall()
  rs_install()
}


case "$CMD" in
  "install") rs_install ;;
  "uninstall") rs_uninstall ;;
  "restart") rs_restart ;;
  *) echo "Unknown command" ; usage ;;
esac
