spring:
  application:
    name: ${job_spring_appname:s1pdgs-jobgenerator}
    
# Logging
logging:
  config: log4j2.yml
 
metadata:
  host: ${catalog_rest_host:metadata-catalog-svc:8080}             # 
  rest-api_nb-retry: 3                                             #  
  rest-api_tempo-retry-ms: 1000                                    # 
  
job-generator:
  diroftasktables: /app/config/task_tables/                        # Directory where the task tables are located
  maxnboftasktable: 1                                              # Maximal number of task tables in memory. The application will not start in there are more than this number tasktables in the directory
  jobgenfixedrate: 100                                             # (Fixed delay) Period between 2 generations
  waitprimarycheck:                                                # Minimal time between two execution of the following method: checking the requirements to generate a job specific to the level
    tempo: 30000
    max-timelife-s: 600
  waitmetadatainput:                                               # Minimal time between two execution of the following method: checking the global requirements to generate a job
    tempo: 60000
    max-timelife-s: 0
  defaultfamily: BLANK                                             # Default family of a output defined in the task table
  inputfamiliesstr: ${products_family-per-type}             # !!!!  Family assignation of a specific output
  outputfamiliesstr: ${products_family-per-type}            # !!!!  Family assignation of a specific output
  type-overlap:                                             # !!!!  Overlap per acquiqition: map {acquisition -> overloap}
    EW: 8.2F
    IW: 7.4F
    SM: 7.7F
    WM: 0.0F
  type-slice-length:                                         # !!!! Slice length per acquiqition: map {acquisition -> slice length}
    EW: 60.0F
    IW: 25.0F
    SM: 25.0F
    WM: 0.0F
  map-type-meta:                                             # !!!!  
    AUX_RES: AUX_RESORB
    SM_RAW__0S: S[1-6]_RAW__0S
    SM_RAW__0A: S[1-6]_RAW__0A
    SM_RAW__0C: S[1-6]_RAW__0C
    SM_RAW__0N: S[1-6]_RAW__0N
    AN_RAW__0S: N[1-6]_RAW__0S
    AN_RAW__0A: N[1-6]_RAW__0A
    AN_RAW__0C: N[1-6]_RAW__0C
    AN_RAW__0N: N[1-6]_RAW__0N
    SM_SL1__1_: S[1-6]_SL1__1_
    
    
status:
  delete-fixed-delay-ms: 1800000                                   # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not
  max-error-counter-processing: 3                                  # the number of consecutive processing errors leading to the state FATALERROR
  max-error-counter-mqi: 30                                        # the number of consecutive MQI errors leading to the state FATALERROR

process:
  level: L0                                                        # Level for job generator 
  hostname: ${HOSTNAME}                                            # Hostname 
  mode: PROD                                                       #  
  params:                                                    # !!!!  Use to configured the dynamic processing parameters in the generated jobOrder. Format map: key: value
    Processing_Mode: NRT                      
    Timeout: 300                     
  loglevelstdout: INFO                                       # !!!!  Use to configured the LogLevelStdout in the generated jobOrder
  loglevelstderr: INFO                                       # !!!!  Use to configured the LogLevelStderr in the generated jobOrder 
  processingstation: WILE                                    # !!!!  Use to configured the ProcessingStation in the generated jobOrder
  outputregexps:                                             # !!!!  Use to specify the regular expression to use for the output in the wrapper.
    SM_RAW__0S: ^S1[A-B]_S[1-6]_RAW__0S.*$                          
    AN_RAW__0S: ^S1[A-B]_N[1-6]_RAW__0S.*$                          
    ZS_RAW__0S: ^S1[A-B]_Z[1-6]_RAW__0S.*$                          
    REP_L0PSA_: ^S1[A|B|_]_OPER_REP_ACQ.*$                          
    REP_EFEP_: ^S1[A|B|_]_OPER_REP_PASS.*.EOF$                      
  mqi:
    host-uri: http://localhost:8081                                # URI of the MQI server APIs
    max-retries: 3                                                 # Nb Max of retry to connect API REST
    tempo-retry-ms: 1000                                           # Tempo before a retry to connect API REST
  appcatalog:
    host-uri: http://app-catalog-svc:8080                          # URI of the applicative data catalog APIs
    max-retries: 3                                                 # Nb Max of retry to connect API 
    tempo-retry-ms: 1000                                           # Tempo before a retry to connect API  
    tm-connect-ms: 5000                                            # Timeout of connections to the API  
  fixed-delay-ms: 200                                              # (Fixed delay) Dealy in milliseconds between 2 next messages
  initial-delay-ms: 5000                                           # Initial delay in missliseconds before the first next message
    
level0:
  dir-extractor-sessions: /data/sessions/                          # Local directory where the EDRS session file are temporarly uploaded to extract the raws list of the session
  
level1:
  pathroutingxmlfile: /app/l1_config/routing.xml
  
pattern-l0-slices:
  regexp: ${pattern-l0-slices_regexp:^([0-9a-z]{2})([0-9a-z]){1}_(([0-9a-z]{2})_RAW__0([0-9a-z_]{3}))_([0-9a-z]{15})_([0-9a-z]{15})_([0-9a-z_]{6})\\w{1,}\\.SAFE(/.*)?$}
  m-group-sat-id: ${pattern-l0-slices_placeMatchSatelliteId:2}
  m-group-mission-id: ${pattern-l0-slices_placeMatchMissionId:1}
  m-group-acquisition: ${pattern-l0-slices_placeMatchAcquisition:4}
  m-group-start-time: ${pattern-l0-slices_placeMatchStartTime:6}
  m-group-stop-time: ${pattern-l0-slices_placeMatchStopTime:7}
  
app-l0-segment:
  name-regexp-pattern: ^([0-9a-z]{2})([0-9a-z]{1})_(([0-9a-z]{2})_RAW__0S([0-9a-z_]{2}))_([0-9a-z]{15})_([0-9a-z]{15})_([0-9a-z_]{6})_([0-9a-z_]{6})\\w{1,}\\.SAFE(/.*)?$
  name-regexp-groups:
    missionId: 1
    satelliteId: 2 
    acquisition: 4
    polarisation: 5
    startTime: 6
    stopTime: 7
    datatakeId: 9

aiop:
  station-codes:
    cgs1: MTI_
    cgs2: SGS_
    cgs3: MPS_
    cgs4: INU_
    erds: WILE
  pt-assembly:
    cgs1: "yes"
    cgs2: "yes"
    cgs3: "yes"
    cgs4: "yes"
    erds: "yes"
  processing-mode:
    cgs1: NRT
    cgs2: NRT
    cgs3: NRT
    cgs4: NRT
    erds: NRT
  reprocessing-mode:
    cgs1: FAST24
    cgs2: FAST24
    cgs3: FAST24
    cgs4: FAST24
    erds: FAST24
  timeout:
    cgs1: 360
    cgs2: 360
    cgs3: 360
    cgs4: 360
    erds: 360
  descramble:
    cgs1: "yes"
    cgs2: "yes"
    cgs3: "yes"
    cgs4: "yes"
    erds: "yes"
  rs-encode:
    cgs1: "no"
    cgs2: "no"
    cgs3: "no"
    cgs4: "yes"
    erds: "yes"

