kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.processing.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount.compression_worker }}
  podManagementPolicy: Parallel
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.processing.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.processor.label.key }}
                operator: In
                values:
                - {{ .Values.processor.label.value.zip }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
        - name: service-logging-config-volume
          mountPath: /app/log
        - name: service-config-volume
          mountPath: /app/config
        - name: data-localwd
          mountPath: /tmp/compression
        - name: s3-upload-cache
          mountPath: {{ .Values.compression_worker.uploadCache.location }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: web
          protocol: TCP
          containerPort: {{ .Values.service.port }}
        env:
        - name: JAVA_XMS
          value: {{ .Values.compression_worker.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.compression_worker.javaOpts.xmx }}
        - name: storage_user_id
          valueFrom:
            secretKeyRef:
              name: obs
              key: USER_ID
        - name: storage_user_secret
          valueFrom:
            secretKeyRef:
              name: obs
              key: USER_SECRET
        envFrom:
        - configMapRef:
            name: s1pdgs-config
        - configMapRef:
            name: s1pdgs-logging-config
        - configMapRef:
            name: s1pdgs-env
        securityContext:
          privileged: false
        livenessProbe:
          httpGet:
            path: /app/status
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5

      - name: {{ .Release.Name }}-mqi
        image: {{ .Values.mqiImage.registry }}/{{ .Values.mqiImage.repository }}/{{ .Values.mqiImage.name }}:{{ .Values.mqiImage.tag }}
        imagePullPolicy: Always
        volumeMounts:
        - name: service-logging-config-volume
          mountPath: /app/log
        - name: mqi-config-volume
          mountPath: /app/config
        ports:
        - name: data
          protocol: TCP
          containerPort: {{ .Values.mqiService.port }}
        env:
        - name: JAVA_XMS
          value: {{ .Values.compression_worker_mqi.javaOpts.xms }}
        - name: JAVA_XMX
          value: {{ .Values.compression_worker_mqi.javaOpts.xmx }}
        envFrom:
        - configMapRef:
            name: s1pdgs-config
        - configMapRef:
            name: s1pdgs-logging-config
        - configMapRef:
            name: s1pdgs-env
        livenessProbe:
          httpGet:
            path: /app/status
            port: {{ .Values.mqiService.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
      tolerations:
      - key: {{ .Values.processor.toleration.key }}
        operator: "Exists"
        effect: {{ .Values.processor.toleration.effect }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      subdomain: {{ .Release.Name }}-svc
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
      volumes:
        - name: service-logging-config-volume
          configMap:
            name: s1pdgs-logging-config
        - name: service-config-volume
          configMap:
            name: {{ .Release.Name }}-service-config
        - name: mqi-config-volume
          configMap:
            name: {{ .Release.Name }}-mqi-config
        - name: s3-upload-cache
          emptyDir:
            medium: {{ .Values.compression_worker.uploadCache.medium }}
            sizeLimit: {{ .Values.compression_worker.uploadCache.size }}
  serviceName: {{ .Release.Name }}-svc
  revisionHistoryLimit: 10
  volumeClaimTemplates:
  - metadata:
      name: data-localwd
    spec:
            #storageClassName: sc-ssd-delete
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 120Gi
