apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: {{ .Release.Name }}-service
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  - name: {{ .Release.Name }}-mqi
    port: {{ .Values.mqiService.port }}
    targetPort: {{ .Values.mqiService.port }}