spring:
  application:
    name: s1pdgs-ingestor
    
# Logging
logging:
  config: log4j2.yml

# KAFKA
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-headless:9092}
  group-id: ingestors
  poll-timeout: 500
  producer-retries: 10
  topic:
    auxiliary-files: ${kafka_topic_auxiliary_files}
    edrs-sessions: ${kafka_topic_edrs_sessions}

#Status
status:
  delete-fixed-delay-ms: 3000
  max-error-counter-aux: 3
  max-error-counter-ses: 3
 
# File
file:
  auxiliary-files:
    local-directory: /data/local-ingestor/auxiliary_files/ # Must contains the last /
    poll-fixed-delay: 1000
    max-msg-per-poll: 5
    executor-pool-size: 5
    clean-empty-directory-rate: 15000
    clean-empty-min-age: 13000
    cache-max-capacity: 10
  session-files:
    local-directory: /data/local-ingestor/edrs_sessions/ # Must contains the last /
    poll-fixed-delay: 1000
    max-msg-per-poll: 5
    executor-pool-size: 5
    clean-empty-directory-rate: 15000
    clean-empty-min-age: 13000
    cache-max-capacity: 70
  backup-directory: /data/local-ingestor/backup/
