# Copyright 2023 Airbus
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: ftp
    protocol: TCP
    port: 21
  - name: ftp-data
    protocol: TCP
    port: 20
  - name: ftp-data-01
    protocol: TCP
    port: 47400
  - name: ftp-data-02
    protocol: TCP
    port: 47401
  - name: ftp-data-03
    protocol: TCP
    port: 47402
  - name: ftp-data-04
    protocol: TCP
    port: 47403
  - name: ftp-data-05
    protocol: TCP
    port: 47404
  - name: ftp-data-06
    protocol: TCP
    port: 47405
  - name: ftp-data-07
    protocol: TCP
    port: 47406
  - name: ftp-data-08
    protocol: TCP
    port: 47407
  - name: ftp-data-09
    protocol: TCP
    port: 47408
  - name: ftp-data-10
    protocol: TCP
    port: 47409
