# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: rs-request-repository
  port: 8080

replicaCount: 1
logLevel: ${logLevel:DEBUG}
logConfig: ${logConfig:log/log4j2.yml}

processing:
  namespace: processing

image:
  registry: artifactory.coprs.esa-copernicus.eu
  repository: werum-docker

  name: rs-core-request-repository
  tag: develop
  
  imagePullSecrets: spring-cloud-dataflow-registry-dockersecret
  
mongodb:
  host: mongodb-0.mongodb-headless.database.svc.cluster.local
  port: 27017
  database: coprs

resources:
  cpu:
    request: "100m"
    limit: "500m"
  ram:
    request: "528Mi"
    limit: "2113Mi"
  javaOpts:
#   xms: "256m"
    xmx: "512m"
