# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  port: 8080

replicaCount:
  request_repository: 1
  
logLevel: ${logLevel:DEBUG}
logConfig: ${logConfig:log/log4j2.yml}

processing:
  namespace: processing
  
worker:
  label:
    key: node-role.kubernetes.io/worker
    value: infra

image:
  name: rs-core-request-repository

request_repository:
  cpu:
    request: "100m"
    limit: "500m"
  ram:
    request: "528Mi"
    limit: "2113Mi"
  javaOpts:
#   xms: "256m"
    xmx: "512m"
