# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

production-trigger-build:
  stage: module
  script:
    - cd production-trigger
    - dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/s1pro-core-production-trigger:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/s1pro-core-production-trigger:$CI_COMMIT_REF_SLUG"
