spring:
  main:
    # Disable spring boot banner
    banner-mode: "off"
  application:
    # Application name
    name: rs-core-metadata-catalog-searchcontroller

# REST controller
server:
  # Port used for publishing REST API
  port: 8080
      
# Logging
logging:
  # Log configuration file
  config: ${log4j_config:log/log4j2.yml}
    
# Elastic Search
elasticsearch:
  # Host of Elasticsearch cluster
  host: ${elastic_host}           
  # Port of Elasticsearch cluster                                
  port: ${elastic_port}   
  # Timeout in milliseconds of connection to the cluster                                        
  connect-timeout-ms: 2000                
  # Timeout in milliseconds of the socket to the cluster                        
  socket-timeout-ms: 10000                                        

# Search Controller configuration
searchcontroller:
  aux-pattern-config: ^([0-9a-z][0-9a-z])([0-9a-z_])(_(OPER|TEST))?_(AMH_ERRMAT|AMV_ERRMAT|AM__ERRMAT|AUX_CAL|AUX_ICE|AUX_INS|AUX_OBMEMC|AUX_PP1|AUX_PP2|AUX_POEORB|AUX_PREORB|AUX_RESORB|AUX_SCS|AUX_WAV|AUX_WND|MPL_ORBPRE|MPL_ORBRES|MPL_ORBSCT|MSK_EW_SLC|MSK__LAND_|MSK_OCEAN_|MSK_OVRPAS)_\w{1,}\.(XML|EOF|SAFE)(/.*)?$
