# Copyright 2023 Airbus
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  port: 8080
  
processing:
  namespace: processing

image:
  registry: artifactory.coprs.esa-copernicus.eu
  repository: rs-docker-private
  
  name: rs-core-mock-ftpserver
  tag: develop
  
  imagePullSecrets: spring-cloud-dataflow-registry-dockersecret
  
worker:
  label:
    key: node-role.kubernetes.io/worker
    value: infra

ftp:
  cpu:
    request: "100m"
    limit: "500m"
  ram:
    request: "10Mi"
    limit: "50Mi"