name: Java Maven CI

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  #build:
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v2

  #    - name: Set up JDK 8
  #      uses: actions/setup-java@v2
  #      with:
  #        java-version: '8'
  #        distribution: 'adopt'

  #    - name: Build jar   
  #      run: |        
  #        mvn clean install -DskipTests=false
  #        mkdir ~/.staging
  #        echo "Fetching jars..."
  #        find . -iname "*.jar" -exec cp {} ~/.staging \;
          

  #    - name: Upload artifact
  #      uses: actions/upload-artifact@v2
  #      with:
  #        name: jars
  #        path: ~/.staging      
      
  docker:
    runs-on: ubuntu-latest    
    
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jars
          path: .staging

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                    
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
              
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}      
