name: Build Base Image

on: 
  push:
    paths:
      - 'rs-container/docker_base/**'
      - '.github/workflows/build-base.yaml'
    branches:
      - '!main'
      - 'release/**'
      - 'develop**'
      - 'stac-nativeapi**'
      - 'cadip**'
      
  workflow_dispatch:

env:
  ARTIFACTORY_BASE: artifactory.coprs.esa-copernicus.eu
  ARTIFACTORY_PROJECT_DOCKER: rs-docker

jobs:
  gg-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: GitGuardian scan
      uses: GitGuardian/ggshield-action@master
      env:
        GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
        GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
        GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }} 

  build-base:
    needs: [gg-scan] 
    runs-on: ubuntu-latest    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-container
        with:
          IMAGE_NAME_SUFFIX: base
          BUILD_CONTEXT: ./rs-container/docker_base
          WERUM_ARTIFACTORY_USER: ${{ secrets.WERUM_ARTIFACTORY_USER }}
          WERUM_ARTIFACTORY_PASSWORD: ${{ secrets.WERUM_ARTIFACTORY_PASSWORD }}
      
      - uses: ./.github/actions/generate-report
        with: 
          COMPONENT: base