name: Build Container for S1 IPF Simulator

on: 
  push:

env:
  IMAGE_NAME: rs-core
  RS_CORE_FOLDER: processing-common
  RS_EXAMPLES_FOLDER: rs-core-examples
  ARTIFACTORY_BASE: artifactory.coprs.esa-copernicus.eu
  ARTIFACTORY_PROJECT_DOCKER: rs-docker
  ARTIFACTORY_PROJECT_DOCKER_PRIVATE: rs-docker-private
  ARTIFACTORY_PROJECT_MAVEN: rs-maven
  ARTIFACTORY_PROJECT_HELM: rs-helm
  ARTIFACTORY_PROJECT_COMMON: rs-zip
  ARTIFACTORY_CORE_PROJECT: rs-core
  ARTIFACTORY_EXAMPLES_PROJECT: rs-core-examples

jobs:
  ipf-container-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ipf: |
          [{image: rs-ipf-s1-aio, dir: docker_s1_ipf_aio},
          {image: rs-ipf-s1-asp, dir: docker_s1_ipf_asp},
          {image: rs-ipf-s1-l1, dir: docker_s1_ipf_l1},
          {image: rs-ipf-s1-l2, dir: docker_s1_ipf_l2},
          {image: rs-ipf-s3-acq, dir: docker_s3_ipf_acq},
          {image: rs-ipf-s3-l0, dir: docker_s3_ipf_l0},
          {image: rs-ipf-s3-mw1, dir: docker_s3_ipf_mw1},
          {image: rs-ipf-s3-ol1-rac, dir: docker_s3_ipf_ol1_rac},
          {image: rs-ipf-s3-ol1-spc, dir: docker_s3_ipf_ol1_spc},
          {image: rs-ipf-s3-ol1, dir: docker_s3_ipf_ol1},
          {image: rs-ipf-s3-ol2, dir: docker_s3_ipf_ol2},
          {image: rs-ipf-s3-pug, dir: docker_s3_ipf_pug},
          {image: rs-ipf-s3-sl1, dir: docker_s3_ipf_sl1},
          {image: rs-ipf-s3-sl2-frp, dir: docker_s3_ipf_sl2_frp},
          {image: rs-ipf-s3-sl2, dir: docker_s3_ipf_sl2},
          {image: rs-ipf-s3-sm2-hy, dir: docker_s3_ipf_sm2_hy},
          {image: rs-ipf-s3-sm2-li, dir: docker_s3_ipf_sm2_li},
          {image: rs-ipf-s3-sm2-si, dir: docker_s3_ipf_sm2_si},
          {image: rs-ipf-s3-sr1, dir: docker_s3_ipf_sr1},
          {image: rs-ipf-s3-sy2-aod, dir: docker_s3_ipf_sy2_aod},
          {image: rs-ipf-s3-sy2-vgs, dir: docker_s3_ipf_sy2_vgs},
          {image: rs-ipf-s3-sy2, dir: docker_s3_ipf_sy2}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | cut -d / -f3-)"
        id: extract_branch

      - uses: ./.github/actions/build-ipf-container
        with:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          IMAGE_NAME: ${{ matrix.ipf.image }}
          BUILD_CONTEXT: ./rs-container/${{ matrix.ipf.dir }}
          WERUM_ARTIFACTORY_USER: ${{ secrets.WERUM_ARTIFACTORY_USER }}
          WERUM_ARTIFACTORY_PASSWORD: ${{ secrets.WERUM_ARTIFACTORY_PASSWORD }}
      
      - uses: ./.github/actions/generate-report
        with: 
          COMPONENT: ${{ matrix.ipf.image }}