spring:
  application:
    name: coprs-native-api

# Logging
logging:
  level:
    root: ERROR
    de.werum.coprs: DEBUG
    esa.s1pdgs.cpoc.prip: DEBUG
    org.springframework: INFO
    org.apache: INFO

# REST controller
server:
  port: 8080

# OpenAPI validator configuration
openapi:
  # Dis/Enableds openapi validation
  disable-validation: false
  # Path exclusion regexp
  path-exclusion-regex: ^\/(app\/status|error|search|openapi\/v3\/doc|openapi\/v3\/doc.yaml|api\/v1\/prip)$
  # Path to spec file
  definition-file: /app/openapi/native-api_openapi.yml

# Native API config
native-api:
  # major version (used as part of the API base path)
  major-version: v1
  # version (to communicate minor changes that are compatible with the major version)
  version: 1.0
  # configuration for internal interfacing to PRIP
  prip-protocol: http
  prip-host: s1pro-prip-frontend-svc.processing.svc.cluster.local
  prip-port: 8080
  # configuration to create PRIP metadata and download links that are externaly accessible
  external-prip-protocol: http
  external-prip-host: coprs.werum.de/prip/odata/v1/
  external-prip-port: 80
  # whether to include the attributes/values of the 'Attributes' collection of the PRIP response into the STAC response
  include-additional-attributes: true
  # default limit
  defaultLimit: 100
  root-catalog-id: catalogs
  root-catalog-title: COPRS STAC
  root-catalog-description: STAC interface for the Copernicus Reference System
  hostname: https://referencesystem.copernicus.eu
  collections:
    s1:
      title: Collection of Sentinel-1
      description: This description holds all published Sentinel-1 products of the Copernicus Reference System
      license: proprietary
    s2:
      title: Collection of Sentinel-2
      description: This description holds all published Sentinel-2 products of the Copernicus Reference System
      license: proprietary
    s3:
      title: Collection of Sentinel-3
      description: This description holds all published Sentinel-3 products of the Copernicus Reference System
      license: proprietary
  lutConfigs:
    "[bbox={value}]":
      - "OData.CSC.Intersects(area=geography'SRID=4326;POLYGON(({value}))'')"
    "[point={value}]": 
      - "OData.CSC.Intersects(area=geography'SRID=4326;POINT({value})')"
    "[productname={value}]": 
      - "contains(Name,'{value}')"
    "[collections={producttype}]":
      - "Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq '{producttype})'"
    "[cloudcover]={min}/{max}":
      - "Attributes/OData.CSC.DoubleAttribute/any(att:att/Name eq 'cloudCover' and att/OData.CSC.DoubleAttribute/Value gt {min})"
      - "Attributes/OData.CSC.DoubleAttribute/any(att:att/Name eq 'cloudCover' and att/OData.CSC.DoubleAttribute/Value lt {max})"
    "[datetime={start}/{stop}]": 
      - "ContentDate/Start gt {start}"
      - "ContentDate/End lt {stop}"
    "[publicationdate={start}/{stop}]":
      - "CreationDate gt {start}"
      - "CreationDate lt {stop}"  
    "[polarisation={value}]":
      - "Attributes/OData.CSC.DoubleAttribute/any(att:att/Name eq 'polarisationChannels' and att/OData.CSC.DoubleAttribute/Value eq {value}"
