spring:
  application:
    name: coprs-native-api

# Logging
logging:
  level:
    root: ERROR
    de.werum.coprs: DEBUG
    esa.s1pdgs.cpoc.prip: DEBUG
    org.springframework: INFO
    org.apache: INFO

# REST controller
server:
  port: 8080

# OpenAPI validator configuration
openapi:
  # Dis/Enableds openapi validation
  disable-validation: false
  # Path exclusion regexp
  path-exclusion-regex: ^\/(app\/status|error|openapi\/v3\/doc|openapi\/v3\/doc.yaml|api\/v1\/prip)$
  # Path to spec file
  definition-file: /app/openapi/native-api_openapi.yml

# url path to generated openapi definition document
springdoc:
  api-docs:
    path: /openapi/v3/doc

# Elastic Search config
elasticsearch:
  # Host of Elasticsearch cluster
  host: prip-elasticsearch
  # Port of Elasticsearch cluster                                        
  port: 9200
  # Timeout in milliseconds of connection to the cluster
  connect-timeout-ms: 2000
  # Timeout in milliseconds of the socket to the cluster
  socket-timeout-ms: 10000

# PRIP client config
prip-client:
  repository:
    # Maximum number of search hits that can be retrieved at a time
    max-search-hits: 1000

# Native API config
native-api:
  # major version (used as part of the API base path)
  major-version: v1
  # version (to communicate minor changes that are compatible with the major version)
  version: 1.0
  # Time in seconds until a download URL expires
  download-url-expiration-time-in-seconds: 600
  # configuration for internal interfacing to PRIP
  prip-protocol: http
  prip-host: s1pro-prip-frontend-svc.processing.svc.cluster.local
  prip-port: 8080
  
  attributes-of-mission:
  - mission-name: s1
    base-attributes:
    - name
    - productionType
    - contentLength
    - publicationDate
    - evictionDate
    - contentDate.start
    - contentDate.end
    attributes-of-product-type:
    - product-type: l0-std
      attributes:
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_operationalMode_string: operationalMode
        attr_swathIdentifier_string: swathIdentifier
        attr_productClass_string: productClass
        attr_productConsolidation_string: productConsolidation
        attr_instrumentConfigurationID_string: instrumentConfigurationId
        attr_missionDatatakeID_long: missionDataTakeId
        attr_sliceProductFlag_boolean: sliceProductFlag
        attr_sliceNumber_long: sliceNumber
        attr_totalSlices_long: totalNumberOfSlice
        attr_polarisationChannels_string: polarisationChannels
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_coordinates_string: coordinates
        attr_productType_string: productType
    - product-type: l0-ann
      attributes:
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_operationalMode_string: operationalMode
        attr_swathIdentifier_string: swathIdentifier
        attr_productClass_string: productClass
        attr_productConsolidation_string: productConsolidation
        attr_instrumentConfigurationID_string: instrumentConfigurationId
        attr_missionDatatakeID_long: missionDataTakeId
        attr_sliceProductFlag_boolean: sliceProductFlag
        attr_sliceNumber_long: sliceNumber
        attr_totalSlices_long: totalNumberOfSlice
        attr_polarisationChannels_string: polarisationChannels
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_coordinates_string: coordinates
        attr_productType_string: productType
    - product-type: l0-cal
      attributes:
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_operationalMode_string: operationalMode
        attr_swathIdentifier_string: swathIdentifier
        attr_productClass_string: productClass
        attr_productConsolidation_string: productConsolidation
        attr_instrumentConfigurationID_string: instrumentConfigurationId
        attr_missionDatatakeID_long: missionDataTakeId
        attr_sliceProductFlag_boolean: sliceProductFlag
        attr_sliceNumber_long: sliceNumber
        attr_totalSlices_long: totalNumberOfSlice
        attr_polarisationChannels_string: polarisationChannels
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_coordinates_string: coordinates
        attr_qualityDataObjectID_string: qualityDataObjectID
        attr_qualityNumOfElement_long: qualityNumOfElement
        attr_qualityNumOfMissingElements_long: qualityNumOfMissingElements
        attr_qualityNumOfCorruptedElements_long: qualityNumOfCorruptedElements
        attr_qualityNumOfRSIncorrigibleElements_long: qualityNumOfRSIncorrigibleElements
        attr_qualityNumOfRSCorrectedElements_long: qualityNumOfRSCorrectedElements
        attr_qualityNumOfRSCorrectedSymbols_long: qualityNumOfRSCorrectedSymbols     
        attr_productType_string: productType
    - product-type: l0-noise
      attributes:
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_operationalMode_string: operationalMode
        attr_swathIdentifier_string: swathIdentifier
        attr_productClass_string: productClass
        attr_productConsolidation_string: productConsolidation
        attr_instrumentConfigurationID_string: instrumentConfigurationId
        attr_missionDatatakeID_long: missionDataTakeId
        attr_sliceProductFlag_boolean: sliceProductFlag
        attr_sliceNumber_long: sliceNumber
        attr_totalSlices_long: totalNumberOfSlice
        attr_polarisationChannels_string: polarisationChannels
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_coordinates_string: coordinates
        attr_qualityDataObjectID_string: qualityDataObjectID
        attr_qualityNumOfElement_long: qualityNumOfElement
        attr_qualityNumOfMissingElements_long: qualityNumOfMissingElements
        attr_qualityNumOfCorruptedElements_long: qualityNumOfCorruptedElements
        attr_qualityNumOfRSIncorrigibleElements_long: qualityNumOfRSIncorrigibleElements
        attr_qualityNumOfRSCorrectedElements_long: qualityNumOfRSCorrectedElements
        attr_qualityNumOfRSCorrectedSymbols_long: qualityNumOfRSCorrectedSymbols     
        attr_productType_string: productType
    - product-type: l0-gps
      attributes:
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_productType_string: productType
    - product-type: l0-hktm
      attributes:
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_productType_string: productType
    - product-type: l1
      attributes:
        attr_processingDate_date: creationTime
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_operationalMode_string: operationalMode
        attr_swathIdentifier_string: swathIdentifier
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_coordinates_string: coordinates
        attr_instrumentConfigurationID_string: instrumentConfigurationId
        attr_missionDatatakeID_long: missionDataTakeId
        attr_polarisationChannels_string: polarisationChannels
        attr_productClass_string: productClass
        attr_productComposition_string: productComposition
        attr_productType_string: productType
        attr_timeliness_string:  safeTimeliness
        attr_sliceProductFlag_boolean: sliceProductFlag
        attr_segmentStartTime_date: segmentStartTime
        attr_sliceNumber_long: sliceNumber
        attr_totalSlices_long: totalNumberOfSlice
    - product-type: l2
      attributes:
        attr_processingDate_date: creationTime
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_beginningDateTime_date: startTime
        attr_endingDateTime_date: stopTime
        attr_startTimeFromAscendingNode_double: startTimeANX
        attr_completionTimeFromAscendingNode_double: stopTimeANX
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_operationalMode_string: operationalMode
        attr_swathIdentifier_string: swathIdentifier
        attr_orbitNumber_long: absoluteStartOrbit
        attr_relativeOrbitNumber_long: relativeStartOrbit
        attr_cycleNumber_long: cycleNumber
        attr_orbitDirection_string: pass
        attr_coordinates_string: coordinates
        attr_instrumentConfigurationID_string: instrumentConfigurationId
        attr_missionDatatakeID_long: missionDataTakeId
        attr_polarisationChannels_string: polarisationChannels
        attr_productClass_string: productClass
        attr_productComposition_string: productComposition
        attr_productType_string: productType
        attr_timeliness_string:  safeTimeliness
        attr_sliceProductFlag_boolean: sliceProductFlag
        attr_segmentStartTime_date: segmentStartTime
        attr_sliceNumber_long: sliceNumber
        attr_totalSlices_long: totalNumberOfSlice
    - product-type: aux-safe
      attributes:
        attr_processingDate_date: processingDate
        attr_processingCenter_string: site
        attr_processorName_string: processorName
        attr_processorVersion_string: processorVersion
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_instrumentShortName_string: instrumentShortName
        attr_productType_string: productType
        attr_beginningDateTime_date: validityStartTime
        attr_productGeneration_date: creationTime
        attr_instrumentConfigurationID_string: instrumentConfigurationId
    - product-type: aux-eof
      attributes:
        attr_platformShortName_string: platformShortName
        attr_platformSerialIdentifier_string: platformSerialIdentifier
        attr_productType_string: productType
        attr_beginningDateTime_date: validityStartTime
        attr_endingDateTime_date: validityStopTime
        attr_processingCenter_string: site
        attr_processorVersion_string: processorVersion
        attr_processingDate_date: creationTime
  - mission-name: s2
    base-attributes:
    - name
    - productionType
    - contentLength
    - publicationDate
    - evictionDate
    - contentDate.start
    - contentDate.end
    attributes-of-product-type:
    - product-type: type1
      attributes:
        attr_testattr1_string: testattr1
        attr_testattr2_date: testattr2
        attr_testattr3_long: testattr3
        attr_testattr4_boolean: testattr4
    - product-type: type2
      attributes:
        attr_testattr5_string: testattr5
        attr_testattr6_date: testattr6
        attr_testattr7_long: testattr7
        attr_testattr8_boolean: testattr8
  - mission-name: s3
    base-attributes:
    - name
    - productionType
    - contentLength
    - publicationDate
    - evictionDate
    - contentDate.start
    - contentDate.end
    attributes-of-product-type:
    - product-type: type3
      attributes:
        attr_testattr9_string: testattr9
        attr_testattr10_date: testattr10
        attr_testattr11_long: testattr11
        attr_testattr12_boolean: testattr12
    - product-type: type4
      attributes:
        attr_testattr13_string: testattr13
        attr_testattr14_date: testattr14
        attr_testattr15_long: testattr15
        attr_testattr16_boolean: testattr16
